'use client';
import AppShell from '@/components/AppShell';
import {useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase';
import {MessageCircle, Send, ShieldCheck, Star} from 'lucide-react';

type Post={id:string;author_id:string;task_id:string|null;body:string;rating:number|null;created_at:string;author:string;comments:CommentRow[]};
type CommentRow={id:string;author_id:string;body:string;created_at:string;author?:string};
type Task={id:string;title:string;status:string};
export default function Community(){
 const [posts,setPosts]=useState<Post[]>([]);const [tasks,setTasks]=useState<Task[]>([]);const [body,setBody]=useState('');const [rating,setRating]=useState(5);const [taskId,setTaskId]=useState('');const [comments,setComments]=useState<Record<string,string>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [userId,setUserId]=useState('');
 async function load(){try{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(user)setUserId(user.id);const {data:postRows,error:pe}=await supabase.from('posts').select('id,author_id,task_id,body,rating,created_at').order('created_at',{ascending:false}).limit(50);if(pe)throw pe;const authors=[...new Set((postRows||[]).map(p=>p.author_id))];const postIds=(postRows||[]).map(p=>p.id);const [{data:profiles},{data:commentRows}]=await Promise.all([authors.length?supabase.from('profiles').select('id,full_name,username').in('id',authors):Promise.resolve({data:[]}),postIds.length?supabase.from('comments').select('id,post_id,author_id,body,created_at').in('post_id',postIds).order('created_at',{ascending:true}):Promise.resolve({data:[]})]);const authorMap=new Map((profiles||[]).map(p=>[p.id,p.full_name||p.username||'UMUNOTA member']));const commentAuthors=[...new Set((commentRows||[]).map(c=>c.author_id))];const {data:commentProfiles}=commentAuthors.length?await supabase.from('profiles').select('id,full_name,username').in('id',commentAuthors):{data:[]};const commentMap=new Map((commentProfiles||[]).map(p=>[p.id,p.full_name||p.username||'UMUNOTA member']));setPosts((postRows||[]).map(p=>({...p,author:authorMap.get(p.author_id)||'UMUNOTA member',comments:(commentRows||[]).filter(c=>c.post_id===p.id).map(c=>({...c,author:commentMap.get(c.author_id)||'UMUNOTA member'}))})));if(user){const {data:taskRows}=await supabase.from('tasks').select('id,title,status').or(`customer_id.eq.${user.id},runner_id.eq.${user.id}`).in('status',['approved','paid']).order('created_at',{ascending:false});setTasks(taskRows||[])}}catch(e){setError(e instanceof Error?e.message:'Unable to load community.')}}
 useEffect(()=>{load()},[]);
 async function publish(e:React.FormEvent){e.preventDefault();if(!userId){location.href='/login?next=/community';return}if(body.trim().length<3)return;setBusy(true);setError('');try{const res=await fetch('/api/posts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({body:body.trim(),taskId:taskId||null,rating:taskId?rating:null})});const data=await res.json();if(!res.ok){setError(data.error||'Unable to publish.');return}setBody('');setTaskId('');await load()}finally{setBusy(false)}}
 async function comment(postId:string){const value=(comments[postId]||'').trim();if(!value)return;if(!userId){location.href='/login?next=/community';return}const supabase=createClient();const {error}=await supabase.from('comments').insert({post_id:postId,author_id:userId,body:value});if(error){setError(error.message);return}setComments(v=>({...v,[postId]:''}));await load()}
 return <AppShell><div className="pageHead"><div><span className="eyebrow">COMMUNITY</span><h1>Task experiences</h1><p>Posts and comments shown here come from the production database.</p></div></div><div className="communityLayout"><div className="feed"><form className="communityComposer" onSubmit={publish}><div className="composerMark"><Send size={20}/></div><div className="composerBody"><h3>Share an experience</h3><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Share something useful and truthful with the UMUNOTA community."/><div className="composerControls"><select value={taskId} onChange={e=>setTaskId(e.target.value)}><option value="">General community post</option>{tasks.map(t=><option key={t.id} value={t.id}>Verified task: {t.title}</option>)}</select>{taskId&&<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(n=><option value={n} key={n}>{n} / 5</option>)}</select>}<button disabled={busy} className="btn btn-gold">{busy?'Publishing...':'Publish'}</button></div>{error&&<div className="errorBox">{error}</div>}</div></form>{posts.map(p=><article className="communityPost" key={p.id}><div className="postHead"><div className="identity"><div className="avatar">{p.author.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</div><div><b>{p.author}</b><small>{p.task_id?'Verified task experience':'Community post'} · {new Date(p.created_at).toLocaleString()}</small></div></div>{p.rating&&<span className="ratingChip"><Star size={15}/>{p.rating}/5</span>}</div><p className="postBody">{p.body}</p>{p.comments.length>0&&<div className="comments">{p.comments.map(c=><div className="comment" key={c.id}><div className="avatar miniAvatar">{(c.author||'U').split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</div><div><b>{c.author}</b><p>{c.body}</p><small>{new Date(c.created_at).toLocaleString()}</small></div></div>)}</div>}<form className="commentForm" onSubmit={e=>{e.preventDefault();comment(p.id)}}><MessageCircle size={17}/><input value={comments[p.id]||''} onChange={e=>setComments({...comments,[p.id]:e.target.value})} placeholder="Write a comment"/><button className="btn btn-dark">Comment</button></form></article>)}</div><aside className="sidecards"><div className="card communityStandard"><ShieldCheck className="goldIcon"/><span className="eyebrow">COMMUNITY STANDARD</span><h3>Useful, truthful and respectful</h3><p className="muted">Task-linked experiences can only reference real approved or paid tasks belonging to the author.</p></div></aside></div></AppShell>;
}
