'use client';
import AppShell from '@/components/AppShell';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {Heart,MessageCircle,Plus,Share2,ShieldCheck,Star} from 'lucide-react';
import {createClient} from '@/lib/supabase';
import {useLanguage} from '@/components/LanguageProvider';

type Media={id:string;post_id:string;media_type:'image'|'video';storage_path:string};
type Post={id:string;author_id:string;task_id:string|null;body:string;rating:number|null;created_at:string;author:string;media:Media[];likes:number;comments:number;shares:number;liked:boolean};
export default function Community(){
 const {t}=useLanguage();const [posts,setPosts]=useState<Post[]>([]);const [userId,setUserId]=useState('');const [error,setError]=useState('');const supabase=useMemo(()=>createClient(),[]);
 const publicUrl=(path:string)=>supabase.storage.from('community-media').getPublicUrl(path).data.publicUrl;
 async function load(){try{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login?next=/community';return}setUserId(user.id);const {data:rows,error:pe}=await supabase.from('posts').select('id,author_id,task_id,body,rating,created_at').order('created_at',{ascending:false}).limit(40);if(pe)throw pe;const ids=(rows||[]).map(p=>p.id),authors=[...new Set((rows||[]).map(p=>p.author_id))];const [{data:profiles},{data:media},{data:likes},{data:comments},{data:shares}]=await Promise.all([authors.length?supabase.from('profiles').select('id,full_name,username').in('id',authors):Promise.resolve({data:[]}),ids.length?supabase.from('post_media').select('id,post_id,media_type,storage_path').in('post_id',ids).order('created_at'):Promise.resolve({data:[]}),ids.length?supabase.from('post_likes').select('post_id,user_id').in('post_id',ids):Promise.resolve({data:[]}),ids.length?supabase.from('comments').select('post_id').in('post_id',ids):Promise.resolve({data:[]}),ids.length?supabase.from('post_shares').select('post_id').in('post_id',ids):Promise.resolve({data:[]})]);const names=new Map((profiles||[]).map(p=>[p.id,p.full_name||p.username||'UMUNOTA member']));setPosts((rows||[]).map(p=>({...p,author:names.get(p.author_id)||'UMUNOTA member',media:(media||[]).filter(m=>m.post_id===p.id),likes:(likes||[]).filter(l=>l.post_id===p.id).length,comments:(comments||[]).filter(c=>c.post_id===p.id).length,shares:(shares||[]).filter(s=>s.post_id===p.id).length,liked:(likes||[]).some(l=>l.post_id===p.id&&l.user_id===user.id)})))}catch(e){setError(e instanceof Error?e.message:'Unable to load community.')}}
 useEffect(()=>{load()},[]);
 async function like(p:Post){if(p.liked){await supabase.from('post_likes').delete().eq('post_id',p.id).eq('user_id',userId);setPosts(v=>v.map(x=>x.id===p.id?{...x,liked:false,likes:Math.max(0,x.likes-1)}:x))}else{const {error}=await supabase.from('post_likes').insert({post_id:p.id,user_id:userId});if(!error)setPosts(v=>v.map(x=>x.id===p.id?{...x,liked:true,likes:x.likes+1}:x))}}
 async function share(p:Post){const url=`${location.origin}/community/${p.id}`;let channel:'native_share'|'copy_link'='copy_link';try{if(navigator.share){await navigator.share({title:'UMUNOTA community post',url});channel='native_share'}else await navigator.clipboard.writeText(url);await supabase.from('post_shares').insert({post_id:p.id,user_id:userId,channel});setPosts(v=>v.map(x=>x.id===p.id?{...x,shares:x.shares+1}:x))}catch{}}
 return <AppShell><div className="communitySocialPage"><header className="communitySocialHeader"><div><span className="eyebrow">{t('community')}</span><h1>{t('communityTitle')}</h1><p>{t('communityIntro')}</p></div><Link href="/community/new" className="btn btn-gold"><Plus size={17}/> {t('newPost')}</Link></header>{error&&<div className="errorBox">{error}</div>}<div className="communitySocialLayout"><main className="socialFeed">{posts.map(p=>{const preview=p.body.length>260?`${p.body.slice(0,260).trim()}…`:p.body;const first=p.media[0];return <article className="socialPostCard" key={p.id}><div className="postHead"><div className="identity"><div className="avatar">{p.author.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</div><div><b>{p.author}</b><small>{p.task_id?t('verifiedTaskExperience'):t('communityPost')} · {new Date(p.created_at).toLocaleString()}</small></div></div>{p.rating&&<span className="ratingChip"><Star size={14}/>{p.rating}/5</span>}</div><Link href={`/community/${p.id}`} className="socialPostBody"><p>{preview}</p>{p.body.length>260&&<span>{t('viewFullPost')}</span>}</Link>{first&&<Link href={`/community/${p.id}`} className="socialMediaPreview">{first.media_type==='video'?<video muted playsInline preload="metadata" src={publicUrl(first.storage_path)}/>:<img src={publicUrl(first.storage_path)} alt="Community post media"/>}{p.media.length>1&&<span className="mediaCount">+{p.media.length-1}</span>}</Link>}<div className="communityStats"><span>{p.likes} {t('likes')}</span><span>{p.comments} {t('comments')}</span><span>{p.shares} {t('shares')}</span></div><div className="communityActions"><button className={p.liked?'active':''} onClick={()=>like(p)}><Heart size={18} fill={p.liked?'currentColor':'none'}/> {t('like')}</button><Link href={`/community/${p.id}#community-comment`}><MessageCircle size={18}/> {t('comment')}</Link><button onClick={()=>share(p)}><Share2 size={18}/> {t('share')}</button></div></article>})}{!posts.length&&!error&&<div className="empty card"><MessageCircle size={30}/><h2>{t('noCommunityPosts')}</h2><p>{t('firstShare')}</p></div>}</main><aside className="communityRightRail"><div className="card communityStandard"><ShieldCheck className="goldIcon"/><span className="eyebrow">{t('communityStandard')}</span><h3>{t('usefulTruthful')}</h3><p className="muted">{t('communityStandardText')}</p></div><div className="card"><span className="eyebrow">{t('postMedia')}</span><h3>{t('photosVideos')}</h3><p className="muted">{t('mediaHelp')}</p></div></aside></div><Link href="/community/new" className="communityFab" aria-label={t('createCommunityPost')}><Plus size={27}/></Link></div></AppShell>;
}
