import Link from 'next/link';
import {Clock3} from 'lucide-react';
import {requireAdmin} from '../../lib/admin';
import {addBusinessPlan,addRevenueEntry,deletePost,setKycStatus,setPaymentStatus,setTaskStatus,setUserRole,updateBusinessPlan,updateDashboardAd,updateRevenueSettings} from './actions';

export const dynamic='force-dynamic';export const revalidate=0;
const taskStatuses=['posted','funded','accepted','in_progress','completion_submitted','payment_requested','approved','disputed','paid','cancelled'];const paymentStatuses=['pending','authorized','requested','released','refunded','disputed','failed'];
export default async function AdminPage(){
 const hasSupabase=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);if(!hasSupabase)return <main className="adminSetupPage"><section className="adminSetupCard"><h1>Connect production Supabase</h1></section></main>;
 const {supabase,profile}=await requireAdmin();
 const admin=(await import('../../lib/supabase-admin')).createAdminSupabaseClient();
 const [profilesRes,tasksRes,paymentsRes,postsRes,adsRes,settingsRes,revenueRes,businessRes]=await Promise.all([
  supabase.from('profiles').select('id,full_name,username,phone,role,kyc_status,rating,created_at').order('created_at',{ascending:false}).limit(20),supabase.from('tasks').select('id,title,status,budget_rwf,customer_id,runner_id,created_at').order('created_at',{ascending:false}).limit(20),admin.from('payments').select('id,task_id,amount_rwf,status,provider,created_at').order('created_at',{ascending:false}).limit(20),supabase.from('posts').select('id,body,author_id,task_id,created_at').order('created_at',{ascending:false}).limit(12),supabase.from('dashboard_ads').select('*').order('slot',{ascending:true}),admin.from('revenue_settings').select('*').eq('id',1).single(),admin.from('revenue_entries').select('*').order('occurred_at',{ascending:false}).limit(50),admin.from('business_plans').select('*').order('created_at',{ascending:false}).limit(30)
 ]);
 const users=profilesRes.data??[],tasks=tasksRes.data??[],payments=paymentsRes.data??[],posts=postsRes.data??[],ads=adsRes.data??[],revenue=revenueRes.data??[],businesses=businessRes.data??[];const settings=settingsRes.data||{task_fee_enabled:true,task_fee_percent:5,advertising_enabled:true,business_enabled:true,business_monthly_price_rwf:25000};
 const totalRevenue=revenue.filter(r=>r.status==='recorded').reduce((s,r)=>s+r.amount_rwf,0);const taskRevenue=revenue.filter(r=>r.source==='task_fee'&&r.status==='recorded').reduce((s,r)=>s+r.amount_rwf,0);const adRevenue=revenue.filter(r=>r.source==='advertising'&&r.status==='recorded').reduce((s,r)=>s+r.amount_rwf,0);const businessRevenue=revenue.filter(r=>r.source==='business_subscription'&&r.status==='recorded').reduce((s,r)=>s+r.amount_rwf,0);const volume=payments.filter(p=>p.status==='released').reduce((s,p)=>s+(p.amount_rwf??0),0);const disputes=tasks.filter(t=>t.status==='disputed').length+payments.filter(p=>p.status==='disputed').length;
 return <main className="adminPage"><aside className="adminSide"><Link className="adminBrand" href="/"><Clock3 size={21}/><b>UMUNOTA</b></Link><span>ADMIN CONTROL</span><nav><a href="#overview">Overview</a><a href="#revenue">Revenue</a><a href="#ads">Advertising</a><a href="#business">Business</a><a href="#users">Users & KYC</a><a href="#tasks">Tasks</a><a href="#payments">Payments</a><a href="#community">Community</a></nav><Link className="adminBack" href="/dashboard">User dashboard</Link></aside><section className="adminMain">
 <header className="adminTop"><div><span className="eyebrow">PLATFORM OPERATIONS</span><h1>Admin dashboard</h1><p>Signed in as {profile.full_name||'Administrator'}. Live production controls.</p></div><span className="adminLive">Production</span></header>
 <section id="overview" className="adminKpis"><article><span>Users</span><b>{users.length}</b><small>{users.filter(u=>u.role==='runner').length} runners</small></article><article><span>Active tasks</span><b>{tasks.filter(t=>!['paid','cancelled'].includes(t.status)).length}</b><small>{tasks.length} recent</small></article><article><span>Total revenue</span><b>{totalRevenue.toLocaleString()} RWF</b><small>recorded revenue</small></article><article><span>Disputes</span><b>{disputes}</b><small>needs attention</small></article></section>
 <section id="revenue" className="adminPanel"><div className="adminSectionHead"><div><span className="eyebrow">REVENUE CONTROL CENTER</span><h2>Three primary revenue engines</h2><p>Admin controls pricing, activation and revenue records.</p></div></div><div className="revenueKpis"><article><span>Task fees</span><b>{taskRevenue.toLocaleString()} RWF</b><small>{settings.task_fee_percent}% configured</small></article><article><span>Advertising</span><b>{adRevenue.toLocaleString()} RWF</b><small>5 dashboard placements</small></article><article><span>Business plans</span><b>{businessRevenue.toLocaleString()} RWF</b><small>{businesses.filter(b=>b.status==='active').length} active</small></article></div><div className="adminRevenueGrid"><form action={updateRevenueSettings} className="adminAdEditor"><h3>Revenue settings</h3><label className="adminCheck"><input type="checkbox" name="task_fee_enabled" defaultChecked={settings.task_fee_enabled}/> Task service fee enabled</label><label>Task fee percentage<input name="task_fee_percent" type="number" min="0" max="30" step="0.1" defaultValue={settings.task_fee_percent}/></label><label className="adminCheck"><input type="checkbox" name="advertising_enabled" defaultChecked={settings.advertising_enabled}/> Advertising enabled</label><label className="adminCheck"><input type="checkbox" name="business_enabled" defaultChecked={settings.business_enabled}/> Business plans enabled</label><label>Default business monthly price (RWF)<input name="business_monthly_price_rwf" type="number" min="0" defaultValue={settings.business_monthly_price_rwf}/></label><button className="adminPrimary">Save revenue settings</button></form><form action={addRevenueEntry} className="adminAdEditor"><h3>Record revenue</h3><label>Source<select name="source"><option value="task_fee">Task fee</option><option value="advertising">Advertising</option><option value="business_subscription">Business subscription</option></select></label><label>Amount (RWF)<input name="amount_rwf" type="number" min="1" required/></label><label>Description<input name="description" required placeholder="What generated this revenue?"/></label><label>Reference<input name="reference" placeholder="Invoice, campaign or task reference"/></label><button className="adminPrimary">Record revenue</button></form></div><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Date</th><th>Source</th><th>Description</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{revenue.map(r=><tr key={r.id}><td>{new Date(r.occurred_at).toLocaleDateString()}</td><td>{String(r.source).replaceAll('_',' ')}</td><td>{r.description}</td><td>{r.reference||'—'}</td><td><b>{r.amount_rwf.toLocaleString()} RWF</b></td></tr>)}</tbody></table></div></section>
 <section id="ads" className="adminPanel"><div className="adminSectionHead"><div><span className="eyebrow">ADVERTISING REVENUE</span><h2>Five dashboard placements</h2><p>Manage content, advertiser, campaign dates and campaign value.</p></div></div><div className="adminAdGrid">{ads.map(ad=><form action={updateDashboardAd} className="adminAdEditor" key={ad.id}><input type="hidden" name="ad_id" value={ad.id}/><div className="adminAdSlot"><span>Placement {ad.slot}</span><label><input type="checkbox" name="is_active" defaultChecked={ad.is_active}/> Active</label></div><label>Advertiser<input name="advertiser_name" defaultValue={ad.advertiser_name||''}/></label><label>Eyebrow<input name="eyebrow" defaultValue={ad.eyebrow}/></label><label>Headline<input name="title" defaultValue={ad.title} required/></label><label>Message<textarea name="body" defaultValue={ad.body} required/></label><div className="adminAdTwo"><label>Button label<input name="cta_label" defaultValue={ad.cta_label||''}/></label><label>Button URL<input name="cta_url" defaultValue={ad.cta_url||''}/></label></div><div className="adminAdTwo"><label>Campaign price (RWF)<input type="number" min="0" name="campaign_price_rwf" defaultValue={ad.campaign_price_rwf||0}/></label><label>Status<select name="campaign_status" defaultValue={ad.campaign_status||'house'}><option value="house">House</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="ended">Ended</option></select></label></div><div className="adminAdTwo"><label>Starts<input type="date" name="campaign_starts_at" defaultValue={ad.campaign_starts_at||''}/></label><label>Ends<input type="date" name="campaign_ends_at" defaultValue={ad.campaign_ends_at||''}/></label></div><button className="adminPrimary">Save placement {ad.slot}</button></form>)}</div></section>
 <section id="business" className="adminPanel"><div className="adminSectionHead"><div><span className="eyebrow">UMUNOTA BUSINESS</span><h2>Business subscriptions</h2><p>Create and manage organizations paying for recurring marketplace access.</p></div></div><form action={addBusinessPlan} className="adminBusinessCreate"><input name="business_name" placeholder="Business name" required/><input name="contact_name" placeholder="Contact name"/><input name="contact_email" type="email" placeholder="Email"/><input name="contact_phone" placeholder="Phone"/><input name="monthly_price_rwf" type="number" min="0" defaultValue={settings.business_monthly_price_rwf}/><select name="status"><option>lead</option><option>active</option><option>paused</option><option>cancelled</option></select><input name="starts_at" type="date"/><input name="renews_at" type="date"/><input name="notes" placeholder="Notes"/><button className="adminPrimary">Add business</button></form><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Business</th><th>Contact</th><th>Status</th><th>Monthly</th><th>Renewal</th><th>Manage</th></tr></thead><tbody>{businesses.map(b=><tr key={b.id}><td><b>{b.business_name}</b></td><td>{b.contact_name||b.contact_email||b.contact_phone||'—'}</td><td>{b.status}</td><td>{b.monthly_price_rwf.toLocaleString()} RWF</td><td>{b.renews_at||'—'}</td><td><form action={updateBusinessPlan} className="adminInline"><input type="hidden" name="plan_id" value={b.id}/><select name="status" defaultValue={b.status}><option>lead</option><option>active</option><option>paused</option><option>cancelled</option></select><input name="monthly_price_rwf" type="number" min="0" defaultValue={b.monthly_price_rwf}/><input name="renews_at" type="date" defaultValue={b.renews_at||''}/><button>Save</button></form></td></tr>)}</tbody></table></div></section>
 <section id="users" className="adminPanel"><div className="adminSectionHead"><h2>Users and KYC</h2></div><div className="adminTableWrap"><table className="adminTable"><thead><tr><th>User</th><th>Role</th><th>KYC</th><th>Rating</th><th>Manage</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.full_name||u.username||'New user'}</b><small>{u.phone||u.id.slice(0,8)}</small></td><td>{u.role}</td><td>{u.kyc_status}</td><td>{Number(u.rating||0).toFixed(1)}</td><td><div className="adminActions"><form action={setUserRole}><input type="hidden" name="user_id" value={u.id}/><select name="role" defaultValue={u.role}><option>customer</option><option>runner</option><option>admin</option></select><button>Save role</button></form><form action={setKycStatus}><input type="hidden" name="user_id" value={u.id}/><select name="kyc_status" defaultValue={u.kyc_status}><option>not_started</option><option>pending</option><option>verified</option><option>rejected</option></select><button>Save KYC</button></form></div></td></tr>)}</tbody></table></div></section>
 <section id="tasks" className="adminPanel"><div className="adminSectionHead"><h2>Task operations</h2></div><div className="adminTableWrap"><table className="adminTable"><tbody>{tasks.map(t=><tr key={t.id}><td><Link href={`/tasks/${t.id}`}><b>{t.title}</b></Link></td><td>{t.budget_rwf.toLocaleString()} RWF</td><td><form className="adminInline" action={setTaskStatus}><input type="hidden" name="task_id" value={t.id}/><select name="status" defaultValue={t.status}>{taskStatuses.map(s=><option key={s}>{s}</option>)}</select><button>Update</button></form></td></tr>)}</tbody></table></div></section>
 <section id="payments" className="adminPanel"><div className="adminSectionHead"><h2>Payments</h2><small>Released volume: {volume.toLocaleString()} RWF</small></div><div className="adminTableWrap"><table className="adminTable"><tbody>{payments.map(p=><tr key={p.id}><td>{p.id.slice(0,8)}</td><td>{p.amount_rwf.toLocaleString()} RWF</td><td>{p.provider||'Not assigned'}</td><td><form className="adminInline" action={setPaymentStatus}><input type="hidden" name="payment_id" value={p.id}/><select name="status" defaultValue={p.status}>{paymentStatuses.map(s=><option key={s}>{s}</option>)}</select><button>Update</button></form></td></tr>)}</tbody></table></div></section>
 <section id="community" className="adminPanel"><div className="adminSectionHead"><h2>Community moderation</h2></div><div className="moderationGrid">{posts.map(p=><article key={p.id}><p>{p.body}</p><form action={deletePost}><input type="hidden" name="post_id" value={p.id}/><button className="adminDanger">Remove post</button></form></article>)}</div></section>
 </section></main>;
}
