'use client';
import AppShell from '@/components/AppShell';
import {useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase';
import {BadgeCheck, Clock3, ShieldCheck, UserRoundCheck} from 'lucide-react';

type Status='not_started'|'pending'|'verified'|'rejected'|'needs_review';
export default function Kyc(){
 const [status,setStatus]=useState<Status>('not_started'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user){location.href='/login?next=/kyc';return} const {data}=await supabase.from('profiles').select('kyc_status').eq('id',user.id).single(); if(data?.kyc_status)setStatus(data.kyc_status as Status);}catch(e){setError(e instanceof Error?e.message:'Unable to load verification status.')}})()},[]);
 async function start(){setBusy(true);setError('');try{const res=await fetch('/api/kyc/session',{method:'POST'});const data=await res.json();if(!res.ok){setError(data.error||'Unable to submit verification request.');return}if(data.verified){setStatus('verified');return}if(data.pending)setStatus('pending');}catch{setError('Unable to submit verification request.')}finally{setBusy(false)}}
 const verified=status==='verified'; const pending=status==='pending'||status==='needs_review';
 return <AppShell><div className="pageHead"><div><span className="eyebrow">IDENTITY VERIFICATION</span><h1>Verify before using the marketplace</h1><p>UMUNOTA keeps verification required for marketplace access, but no paid external verification service is needed.</p></div><div className={`kycState ${verified?'verifiedState':''}`}><ShieldCheck size={22}/><span>{status.replaceAll('_',' ')}</span></div></div><div className="kycLayout"><section className="card verificationJourney"><div className="section-head"><div><span className="eyebrow">MANUAL REVIEW</span><h2>No paid KYC credits required</h2></div></div><div className="verificationFeature"><UserRoundCheck/><div><b>Submit a review request</b><p>Your account enters a pending state for UMUNOTA administrator review instead of opening a paid third-party verification session.</p></div></div><div className="verificationFeature"><ShieldCheck/><div><b>Verification is still required</b><p>This does not bypass eligibility, age, identity, or marketplace rules. An administrator must approve the account before posting or accepting tasks.</p></div></div><div className="verificationFeature"><BadgeCheck/><div><b>Verified marketplace access</b><p>Only an approved verification status unlocks marketplace participation.</p></div></div></section><aside className="sidecards"><div className="card verificationCard"><span className="eyebrow">CURRENT STATUS</span><h2>{verified?'Identity verified':pending?'Verification under review':'Verification required'}</h2><p>{verified?'Your account can post and accept eligible tasks.':pending?'Your request is waiting for manual review. You do not need to pay for external verification credits.':'Submit your account for manual review to begin verification.'}</p>{!verified&&<button disabled={busy||pending} onClick={start} className="btn btn-gold btn-wide asyncBtn" aria-busy={busy}>{busy?<><Clock3 size={18} className="spinIcon"/> Submitting...</>:pending?<><Clock3 size={18}/> Review pending</>:<><Clock3 size={18}/> Submit for manual review</>}</button>}{verified&&<a className="btn btn-gold btn-wide" href="/dashboard"><Clock3 size={17}/> Continue to dashboard</a>}{error&&<div className="errorBox">{error}</div>}</div><div className="card privacyCard"><ShieldCheck className="goldIcon"/><span className="eyebrow">PRIVACY</span><h3>No public identity-document exposure</h3><p className="muted">Other members see verification status only. Manual review must still follow UMUNOTA privacy and eligibility rules.</p></div></aside></div></AppShell>;
}
