'use client';
import AppShell from '@/components/AppShell';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Camera,Clock3,Image as ImageIcon,Video,X,Zap} from 'lucide-react';
import {createClient} from '@/lib/supabase';

type Task={id:string;title:string};
async function optimizeImage(file:File){if(!file.type.startsWith('image/')||file.type==='image/gif'||file.size<450*1024)return file;try{const bitmap=await createImageBitmap(file);const max=1600;const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)return file;ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/webp',.78));if(!blob||blob.size>=file.size)return file;return new File([blob],file.name.replace(/\.[^.]+$/,'.webp'),{type:'image/webp',lastModified:Date.now()})}catch{return file}}
export default function NewCommunityPost(){
 const router=useRouter();const [body,setBody]=useState('');const [taskId,setTaskId]=useState('');const [rating,setRating]=useState(5);const [tasks,setTasks]=useState<Task[]>([]);const [files,setFiles]=useState<File[]>([]);const [busy,setBusy]=useState(false);const [optimizing,setOptimizing]=useState(false);const [error,setError]=useState('');const [userId,setUserId]=useState('');
 useEffect(()=>{(async()=>{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login?next=/community/new';return}setUserId(user.id);const {data}=await supabase.from('tasks').select('id,title').or(`customer_id.eq.${user.id},runner_id.eq.${user.id}`).in('status',['approved','paid']).order('created_at',{ascending:false});setTasks(data||[])})()},[]);
 async function pick(next:FileList|null){if(!next)return;setOptimizing(true);setError('');try{const selected=Array.from(next).filter(f=>f.type.startsWith('image/')||f.type.startsWith('video/')).slice(0,4);if(selected.some(f=>f.type.startsWith('video/')&&f.size>20*1024*1024)){setError('Each video must be 20 MB or smaller. Large video transcoding is not performed in the browser.');return}const optimized=await Promise.all(selected.map(optimizeImage));if(optimized.some(f=>f.size>20*1024*1024)){setError('Each media file must be 20 MB or smaller after optimization.');return}setFiles(optimized)}finally{setOptimizing(false)}}
 async function publish(e:React.FormEvent){e.preventDefault();if(!userId||body.trim().length<3)return;setBusy(true);setError('');const supabase=createClient();const uploaded:string[]=[];try{const media=[];for(const file of files){const ext=(file.name.split('.').pop()||'bin').replace(/[^a-zA-Z0-9]/g,'');const path=`${userId}/${crypto.randomUUID()}.${ext}`;const {error:ue}=await supabase.storage.from('community-media').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'31536000'});if(ue)throw ue;uploaded.push(path);media.push({storagePath:path,mediaType:file.type.startsWith('video/')?'video':'image',mimeType:file.type,sizeBytes:file.size})}const res=await fetch('/api/posts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({body:body.trim(),taskId:taskId||null,rating:taskId?rating:null,media})});const d=await res.json();if(!res.ok)throw new Error(d.error||'Unable to publish post.');router.replace(`/community/${d.post.id}`);router.refresh()}catch(e){for(const path of uploaded)await supabase.storage.from('community-media').remove([path]);setError(e instanceof Error?e.message:'Unable to publish post.')}finally{setBusy(false)}}
 const originalSummary=files.length?`${files.reduce((s,f)=>s+f.size,0)/1024/1024}`:'';
 return <AppShell><div className="communityNewWrap"><div className="communityComposeHead"><button className="iconButton" onClick={()=>router.back()} aria-label="Close"><X size={20}/></button><div><span className="eyebrow">NEW COMMUNITY POST</span><h1>Share with UMUNOTA</h1></div></div><form className="communityNewCard" onSubmit={publish}><textarea autoFocus value={body} onChange={e=>setBody(e.target.value)} placeholder="What would be useful for the UMUNOTA community to know?" maxLength={3000}/><div className="mediaPicker"><label><ImageIcon size={18}/> Photo or video<input type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" multiple onChange={e=>pick(e.target.files)}/></label><span>{optimizing?'Optimizing...':`${files.length}/4 files`}</span></div><div className="mediaOptimizeNote"><Zap size={16}/><span><b>Speed optimization:</b> large JPEG/PNG/WebP images are resized and compressed to WebP before upload. Videos stay in their original browser-compatible format and are capped at 20 MB.</span></div>{files.length>0&&<div className="communitySelectedMedia">{files.map((f,i)=><div key={`${f.name}-${i}`}>{f.type.startsWith('video/')?<Video size={18}/>:<Camera size={18}/>}<span>{f.name} · {(f.size/1024/1024).toFixed(1)} MB</span><button type="button" onClick={()=>setFiles(v=>v.filter((_,x)=>x!==i))}><X size={15}/></button></div>)}</div>}<div className="communityComposerOptions"><select value={taskId} onChange={e=>setTaskId(e.target.value)}><option value="">General community post</option>{tasks.map(t=><option key={t.id} value={t.id}>Verified task: {t.title}</option>)}</select>{taskId&&<select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select>}</div>{error&&<div className="errorBox">{error}</div>}<button disabled={busy||optimizing||body.trim().length<3} className="btn btn-gold btn-wide asyncBtn">{busy?<><Clock3 size={17} className="spinIcon"/> Publishing...</>:<><Clock3 size={17}/> Publish post</>}</button></form></div></AppShell>;
}
