'use client';
import AppShell from '@/components/AppShell';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase';
import {CreditCard, ShieldCheck, WalletCards} from 'lucide-react';

type Payment={id:string;task_id:string;amount_rwf:number;status:string;provider:string|null;created_at:string;customer_id:string;runner_id:string|null};
export default function Payments(){
 const [rows,setRows]=useState<Payment[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login?next=/payments';return}const {data,error}=await supabase.from('payments').select('id,task_id,amount_rwf,status,provider,created_at,customer_id,runner_id').or(`customer_id.eq.${user.id},runner_id.eq.${user.id}`).order('created_at',{ascending:false});if(error)throw error;setRows(data||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load payments.')}finally{setLoading(false)}})()},[]);
 const protectedTotal=useMemo(()=>rows.filter(r=>['pending','authorized','requested','disputed'].includes(r.status)).reduce((s,r)=>s+r.amount_rwf,0),[rows]);
 const released=useMemo(()=>rows.filter(r=>r.status==='released').reduce((s,r)=>s+r.amount_rwf,0),[rows]);
 return <AppShell><div className="pageHead"><div><span className="eyebrow">PAYMENTS</span><h1>Payment activity</h1><p>Track Mobile Money funding and payouts connected to your UMUNOTA tasks.</p></div></div><div className="paymentStats"><div className="metricCard"><WalletCards/><span>Protected in tasks</span><b>{protectedTotal.toLocaleString()} RWF</b><small>Pending, confirmed, requested or disputed</small></div><div className="metricCard"><CreditCard/><span>Released</span><b>{released.toLocaleString()} RWF</b><small>Confirmed task payouts</small></div><div className="metricCard"><ShieldCheck/><span>Payment method</span><b>Mobile Money</b><small>Supported Rwanda mobile-money networks</small></div></div>{error&&<div className="errorBox">{error}</div>}{loading?<div className="card loadingCard">Loading payment records...</div>:<section className="paymentLedger"><div className="section-head"><div><span className="eyebrow">TRANSACTIONS</span><h2>Task payments</h2></div></div>{rows.map(p=><Link href={`/tasks/${p.task_id}`} className="paymentRow productionPaymentRow" key={p.id}><div className="paymentIcon"><CreditCard size={18}/></div><div className="paymentName"><b>Task payment</b><span>Mobile Money · {new Date(p.created_at).toLocaleString()}</span></div><span className="taskState">{p.status}</span><b>{p.amount_rwf.toLocaleString()} RWF</b></Link>)}{!rows.length&&<div className="empty"><CreditCard size={30} className="goldIcon"/><h3>No payment records yet</h3><p>Your payment records will appear after you fund a task.</p></div>}</section>}<div className="notice">A payment is marked complete only after the Mobile Money transfer is confirmed.</div></AppShell>;
}
