'use client';
import AppShell from '@/components/AppShell';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase';
import {BadgeCheck, Search, UserRound} from 'lucide-react';

type Runner={id:string;full_name:string|null;username:string|null;avatar_url:string|null;rating:number|null;rating_count:number|null;kyc_status:string;role:string;show_in_runner_directory:boolean};
export default function Runners(){
 const [q,setQ]=useState('');const [runners,setRunners]=useState<Runner[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{try{const supabase=createClient();const {data,error}=await supabase.from('profiles').select('id,full_name,username,avatar_url,rating,rating_count,kyc_status,role,show_in_runner_directory').eq('role','runner').eq('kyc_status','verified').eq('show_in_runner_directory',true).order('rating',{ascending:false});if(error)throw error;setRunners(data||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load runners.')}finally{setLoading(false)}})()},[]);
 const filtered=useMemo(()=>runners.filter(r=>`${r.full_name||''} ${r.username||''}`.toLowerCase().includes(q.toLowerCase())),[runners,q]);
 return <AppShell><div className="pageHead"><div><span className="eyebrow">VERIFIED RUNNERS</span><h1>Find a runner</h1><p>Only identity-verified runners who choose to appear in the directory are listed here.</p></div></div><div className="runnerSearch customSearch"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search verified runners"/></div>{error&&<div className="errorBox">{error}</div>}{loading?<div className="card loadingCard">Loading verified runners...</div>:<div className="runnerGrid">{filtered.map(r=>{const name=r.full_name||r.username||'UMUNOTA runner';const initials=name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();return <article className="runnerCard customRunnerCard" id={r.id} key={r.id}><div className="runnerHero">{r.avatar_url?<div className="avatar avatarXl"><img src={r.avatar_url} alt=""/></div>:<div className="avatar avatarXl">{initials}</div>}<span className="verifiedBadge"><BadgeCheck size={15}/> Verified</span></div><h2>{name}</h2><div className="ratingLine"><span>{Number(r.rating||0).toFixed(1)} rating</span><span>{r.rating_count||0} ratings</span></div><div className="verifiedRunnerNotice"><UserRound size={18}/><span>Identity verification completed before marketplace access.</span></div><Link href="/tasks/new" className="btn btn-gold btn-wide">Post a task</Link></article>})}{!filtered.length&&<div className="empty card"><UserRound size={32} className="goldIcon"/><h3>No verified runners found</h3><p>Verified runner accounts will appear as people complete onboarding and enable directory visibility.</p></div>}</div>}</AppShell>;
}
