import Link from 'next/link';
import {BadgeCheck, Box, CalendarClock, Clock3, CreditCard, FileCheck2, MapPin, MessageSquareText, PackageCheck, Printer, ShieldCheck, ShoppingBasket, Smartphone, UserRoundCheck, UsersRound, Wrench, WashingMachine} from 'lucide-react';

const services=[
  {icon:ShoppingBasket,title:'Market runs',body:'Groceries, household items and quick purchases.'},
  {icon:Box,title:'Pickup & delivery',body:'Documents, parcels and everyday errands.'},
  {icon:Wrench,title:'Take to repair',body:'Phones, shoes, clothes and other small repairs.'},
  {icon:WashingMachine,title:'Laundry & cleaning',body:'Pickup, drop-off and trusted local help.'},
  {icon:Printer,title:'Print & collect',body:'Print documents and have them collected for you.'},
  {icon:Clock3,title:'Anything safe & local',body:'Describe a safe, legal local task and find someone nearby.'},
];
const taskExamples=[
  {title:'Buy groceries from Kimironko Market',category:'Market shopping',location:'Gasabo, Kigali',budget:'18,500 RWF',time:'Today · 18:30',status:'Runner matching'},
  {title:'Collect printed documents and deliver them',category:'Documents',location:'Nyarugenge, Kigali',budget:'4,500 RWF',time:'Tomorrow · 09:00',status:'Ready to fund'},
  {title:'Take my phone to repair and return it',category:'Repair errand',location:'Kicukiro, Kigali',budget:'7,000 RWF',time:'Tomorrow · 15:00',status:'Verified runner required'},
];
const audiences=[
  {icon:UsersRound,title:'For customers',body:'Save time by posting everyday errands with a clear location, budget, deadline and completion requirement.'},
  {icon:UserRoundCheck,title:'For runners',body:'Use your available time to complete safe local tasks, build ratings and create a trusted work history.'},
  {icon:CreditCard,title:'For payments',body:'Task-linked MTN and Airtel Mobile Money requests are handled through Paypack and reconciled from provider confirmation.'},
  {icon:ShieldCheck,title:'For trust',body:'Identity verification is required before marketplace participation, with task events and evidence kept in the record.'},
];

export default function Page(){return <main className="landing">
  <nav className="landingNav"><Link className="landingBrand simpleLandingBrand" href="/"><Clock3 size={24}/><b>UMUNOTA</b></Link><div className="landingLinks"><a href="#tasks">Task examples</a><a href="#services">Services</a><a href="#how">How it works</a><a href="#trust">Trust</a></div><div className="landingActions"><Link href="/login">Log in</Link><Link className="btn btn-gold" href="/signup"><Clock3 size={16}/> Get started</Link></div></nav>

  <section className="landingHero"><div className="landingHeroCopy"><span className="landingPill">PEOPLE · TIME · SOLUTIONS</span><h1>Everyday help,<br/><span className="gold">organized around trust.</span></h1><p>UMUNOTA is Rwanda’s local task marketplace for the small jobs that take your time: shopping, pickups, repair drop-offs, document collection, laundry errands and other safe everyday tasks.</p><div className="landingCtas"><Link className="btn btn-gold" href="/signup"><Clock3 size={17}/> Post your first task</Link><Link className="btn btn-dark" href="/login">Explore as a runner</Link></div><div className="landingTrust"><span><BadgeCheck size={15}/> Verified marketplace access</span><span><ShieldCheck size={15}/> Tracked task flow</span><span><PackageCheck size={15}/> Proof and ratings</span></div></div><div className="landingVisual landingVisualClean"><div className="landingClockWordmark"><Clock3 size={70}/><strong>UMUNOTA</strong><small>People. Time. Solutions.</small></div><div className="floatingTask one"><b>Market pickup</b><span>18,500 RWF</span><small>Runner matching</small></div><div className="floatingTask two"><b>Print & deliver</b><span>4,500 RWF</span><small>Scheduled for tomorrow</small></div><div className="floatingTask three"><b>Repair errand</b><span>7,000 RWF</span><small>Verified runner required</small></div></div></section>

  <section className="landingValueStrip"><article><Clock3/><div><b>Post in minutes</b><span>Tell UMUNOTA what needs to be done.</span></div></article><article><BadgeCheck/><div><b>Verified participation</b><span>Both sides verify before marketplace actions.</span></div></article><article><CreditCard/><div><b>Provider-backed payments</b><span>Mobile money activity stays linked to the task.</span></div></article><article><FileCheck2/><div><b>Track the record</b><span>Status, evidence and ratings stay connected.</span></div></article></section>

  <section id="tasks" className="landingSection landingExamples"><div className="landingSectionHead"><span className="eyebrow">WHAT A TASK LOOKS LIKE</span><h2>Clear tasks make it easier to match, complete and pay.</h2><p>These are example task cards that show how UMUNOTA organizes the information both sides need before work begins.</p></div><div className="landingTaskGrid">{taskExamples.map(t=><article className="landingTaskCard" key={t.title}><div className="landingTaskCardTop"><span>{t.category}</span><b>{t.budget}</b></div><h3>{t.title}</h3><div className="landingTaskMeta"><span><MapPin size={15}/>{t.location}</span><span><CalendarClock size={15}/>{t.time}</span></div><div className="landingTaskStatus"><BadgeCheck size={15}/>{t.status}</div></article>)}</div><div className="landingExamplesFoot"><p>Real marketplace tasks are shown only according to account access and task visibility rules. These cards are examples for explaining the product.</p><Link className="btn btn-gold" href="/signup"><Clock3 size={16}/> Create a real task</Link></div></section>

  <section id="services" className="landingSection"><div className="landingSectionHead"><span className="eyebrow">EVERYDAY HELP</span><h2>One marketplace for many small real-world tasks.</h2><p>UMUNOTA is not limited to one delivery category. Users describe the safe, legal task they need and the marketplace helps organize the work.</p></div><div className="landingServiceGrid">{services.map(({icon:Icon,title,body})=><article key={title}><span className="landingServiceIcon"><Icon size={22}/></span><h3>{title}</h3><p>{body}</p></article>)}</div></section>

  <section className="landingSection landingAudience"><div className="landingSectionHead"><span className="eyebrow">ONE SYSTEM, DIFFERENT NEEDS</span><h2>Customers, runners, trust and payments in one flow.</h2></div><div className="landingAudienceGrid">{audiences.map(({icon:Icon,title,body})=><article key={title}><Icon size={24}/><h3>{title}</h3><p>{body}</p></article>)}</div></section>

  <section id="how" className="landingSection landingSteps"><div className="landingSectionHead"><span className="eyebrow">HOW IT WORKS</span><h2>From “I need help” to a completed record.</h2><p>Each stage has a clear purpose so customers and runners know what must happen next.</p></div><div className="stepGrid"><article><b>01</b><h3>Verify account</h3><p>Complete identity verification before posting or accepting marketplace work.</p></article><article><b>02</b><h3>Post the task</h3><p>Add the job, selected location, budget, category and date/time deadline.</p></article><article><b>03</b><h3>Fund and accept</h3><p>The customer requests funding and an eligible verified runner can accept after confirmation.</p></article><article><b>04</b><h3>Complete and review</h3><p>The runner completes the task, submits the required evidence and requests approval.</p></article><article><b>05</b><h3>Approve or dispute</h3><p>The customer reviews the result and either approves the work or opens a dispute.</p></article><article><b>06</b><h3>Payout and reputation</h3><p>Provider-confirmed payout closes the task and the experience can contribute to ratings and history.</p></article></div></section>

  <section className="landingSection landingProductFlow"><div className="landingFlowCopy"><span className="eyebrow">THE UMUNOTA RECORD</span><h2>More than matching two people.</h2><p>UMUNOTA keeps the task context together: who posted it, who accepted it, where it happens, when it is due, what was agreed, how payment moved and what happened during completion.</p><div className="landingFlowChecklist"><span><Smartphone size={17}/> Mobile-first experience</span><span><MessageSquareText size={17}/> Community and task history</span><span><FileCheck2 size={17}/> Completion evidence and audit trail</span><span><CreditCard size={17}/> Task-linked payment records</span></div></div><div className="landingLifecycle"><div>Posted</div><div>Funded</div><div>Accepted</div><div>In progress</div><div>Completion submitted</div><div>Payment requested</div><div>Approved</div><div>Paid</div></div></section>

  <section id="trust" className="landingTrustSection"><div><span className="eyebrow">BUILT FOR TRUST</span><h2>Marketplace access starts with verification.</h2><p>UMUNOTA combines identity verification, server-checked task transitions, provider-confirmed payment state, ratings and moderation. Uploading a document alone does not make an account verified; the verification result must come from the configured provider.</p><Link className="btn btn-gold" href="/signup"><Clock3 size={16}/> Create account</Link></div><div className="trustTiles"><article><b>Verified</b><span>Identity before posting or accepting</span></article><article><b>Tracked</b><span>Task events and evidence</span></article><article><b>Provider-backed</b><span>MTN and Airtel through Paypack</span></article><article><b>Local</b><span>Designed around Rwanda’s everyday work</span></article></div></section>

  <section className="landingSection landingFinalCta"><Clock3 size={42}/><div><span className="eyebrow">START WITH ONE TASK</span><h2>What would you get done if you had another pair of hands?</h2><p>Create your UMUNOTA account, verify your identity and post a clear task when you are ready.</p></div><Link className="btn btn-gold" href="/signup">Get started</Link></section>

  <footer className="landingFooter"><div><Link className="landingBrand simpleLandingBrand" href="/"><Clock3 size={22}/><b>UMUNOTA</b></Link><p>People. Time. Solutions.</p></div><div><Link href="/login">Log in</Link><Link href="/signup">Create account</Link><Link href="/community">Community</Link><Link href="/kyc">Trust center</Link></div><small>© 2026 UMUNOTA. Safe, legal everyday tasks only.</small></footer>
</main>}
