'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {Bell, Building2, CircleUserRound, Clock3, CreditCard, FileText, Globe2, Home, MapPin, MessageSquareText, Search, ShieldCheck, UsersRound, ClipboardList, Plus, ChevronDown, MoreHorizontal, X} from 'lucide-react';
import {createClient} from '@/lib/supabase';
import InstallBanner from './InstallBanner';
import {languageOptions,useLanguage} from './LanguageProvider';

const nav=[[Home,'home','/dashboard'],[Plus,'postTask','/tasks/new'],[UsersRound,'findRunner','/runners'],[ClipboardList,'myTasks','/tasks'],[Building2,'business','/business'],[MessageSquareText,'community','/community'],[CreditCard,'payments','/payments'],[ShieldCheck,'trust','/kyc'],[CircleUserRound,'profile','/profile']] as const;
const mobilePrimary=[[Home,'home','/dashboard'],[Plus,'postTask','/tasks/new'],[ClipboardList,'myTasks','/tasks'],[MessageSquareText,'community','/community']] as const;
const mobileMore=[[Building2,'business','/business'],[UsersRound,'findRunner','/runners'],[CreditCard,'payments','/payments'],[ShieldCheck,'trust','/kyc'],[CircleUserRound,'profile','/profile']] as const;
const areas=['Kigali','Gasabo','Kicukiro','Nyarugenge','Musanze','Huye','Rubavu'];

export default function AppShell({children}:{children:React.ReactNode}){
 const pathname=usePathname();const [search,setSearch]=useState('');const [area,setArea]=useState('Kigali');const [name,setName]=useState('Account');const [moreOpen,setMoreOpen]=useState(false);const {lang,setLang,t}=useLanguage();
 useEffect(()=>{setMoreOpen(false)},[pathname]);useEffect(()=>{(async()=>{try{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from('profiles').select('full_name').eq('id',user.id).single();if(data?.full_name)setName(data.full_name)}catch{}})()},[]);
 const initials=name==='Account'?'U':name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();const isActive=(href:string)=>pathname===href||(href!='/tasks'&&pathname.startsWith(href+'/'));
 return <div className="shell"><aside className="sidebar"><Link href="/dashboard" className="logo simpleBrand"><Clock3 size={24}/><span><b>UMUNOTA</b><small>People. Time. Solutions.</small></span></Link><nav className="nav">{nav.map(([Icon,key,href])=><Link className={isActive(href)?'active':''} href={href} key={href}><span className="navIcon"><Icon size={18}/></span><span className="label">{t(key)}</span></Link>)}</nav><div className="sideTrust"><ShieldCheck size={18}/><div><b>{t('verifiedMarketplace')}</b><small>{t('verifiedDetail')}</small><Link href="/legal">Legal & Safety</Link></div></div></aside><main className="main"><InstallBanner/><header className="topbar"><form className="searchBox" onSubmit={e=>{e.preventDefault();location.href='/tasks/new?title='+encodeURIComponent(search)}}><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('searchPlaceholder')}/><button>{t('search')}</button></form><div className="locationSelect"><MapPin size={17}/><select value={area} onChange={e=>setArea(e.target.value)} aria-label={t('location')}>{areas.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></div><label className="languageSwitcher"><Globe2 size={16}/><select aria-label={t('language')} value={lang} onChange={e=>setLang(e.target.value as any)}>{languageOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><button className="iconButton" aria-label="Notifications"><Bell size={18}/></button><Link className="profileChip" href="/profile"><span className="avatar smallAvatar">{initials}</span><span className="profileName">{name}</span></Link></header>{children}</main><nav className="mobileBottomNav">{mobilePrimary.map(([Icon,key,href])=><Link href={href} className={isActive(href)?'active':''} key={href}><Icon size={20}/><span>{t(key)}</span></Link>)}<button className={moreOpen?'active':''} onClick={()=>setMoreOpen(v=>!v)} aria-label={t('more')}><MoreHorizontal size={21}/><span>{t('more')}</span></button></nav>{moreOpen&&<div className="mobileNavSheetBackdrop" onClick={()=>setMoreOpen(false)}><section className="mobileNavSheet" onClick={e=>e.stopPropagation()}><div className="mobileNavSheetHead"><div><b>UMUNOTA</b><small>{t('verifiedDetail')}</small></div><button onClick={()=>setMoreOpen(false)} aria-label="Close"><X size={20}/></button></div><div className="mobileNavSheetGrid">{mobileMore.map(([Icon,key,href])=><Link href={href} className={isActive(href)?'active':''} key={href}><Icon size={21}/><span>{t(key)}</span></Link>)}<Link href="/legal"><FileText size={21}/><span>Legal & Safety</span></Link></div><label className="languageSwitcher mobileLanguage"><Globe2 size={16}/><select value={lang} onChange={e=>setLang(e.target.value as any)}>{languageOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></section></div>}</div>;
}
