'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';

type Lang='en'|'rw'|'fr'|'sw';
type Dict=Record<string,string>;
const dictionaries:Record<Lang,Dict>={
 en:{home:'Home',postTask:'Post task',findRunner:'Find runner',myTasks:'My tasks',business:'Business',community:'Community',payments:'Payments',trust:'Trust & KYC',profile:'Profile',settings:'Settings',more:'More',search:'Search',searchPlaceholder:'What do you need done?',verifiedMarketplace:'Verified marketplace',verifiedDetail:'Identity · tracked work · protected payments',language:'Language',location:'Location',createTask:'Create task',taskTitle:'Task title',taskDetails:'Task details',budget:'Budget (RWF)',category:'Category',serviceLocation:'Service location',deadline:'Deadline',completionProof:'Completion proof',publishTask:'Publish verified task',useGps:'Use my GPS',mapHint:'Tap the map to place the exact task pin.',exactPin:'Exact pin',viewGoogleMaps:'View on Google Maps',marketplace:'UMUNOTA MARKETPLACE',welcome:'Welcome',timeMatters:'Your time matters.',trustedHelp:'Get trusted help, safely.',heroCopy:'Verified people, tracked task stages, real database records and provider-backed payments.',verifyStart:'Verify to start',activeTasks:'Active tasks',taskValue:'Task value',identity:'Identity',verified:'Verified',required:'Required',recentActivity:'Recent activity',viewAll:'View all',yourTasks:'YOUR TASKS',verifiedRunners:'VERIFIED RUNNERS',availablePeople:'Available people',browseRunners:'Browse runners',latestExperiences:'Latest experiences',noTasks:'No tasks yet',noTasksCopy:'Your real tasks will appear here after you publish or accept one.',noPosts:'No community posts yet.'},
 rw:{home:'Ahabanza',postTask:'Tanga akazi',findRunner:'Shaka umufasha',myTasks:'Imirimo yanjye',business:'Business',community:'Umuryango',payments:'Kwishyura',trust:'Umutekano & KYC',profile:'Umwirondoro',settings:'Igenamiterere',more:'Ibindi',search:'Shaka',searchPlaceholder:'Ni iki ushaka ko bagufasha gukora?',verifiedMarketplace:'Isoko ry’abagenzuwe',verifiedDetail:'Umwirondoro · gukurikirana akazi · kwishyura neza',language:'Ururimi',location:'Aho uri',createTask:'Tanga akazi',taskTitle:'Umutwe w’akazi',taskDetails:'Ibisobanuro by’akazi',budget:'Ingengo y’imari (RWF)',category:'Icyiciro',serviceLocation:'Aho akazi gakorerwa',deadline:'Igihe ntarengwa',completionProof:'Ikimenyetso cy’uko karangiye',publishTask:'Tangaza akazi kagenzuwe',useGps:'Koresha GPS yanjye',mapHint:'Kanda ku ikarita ushyire ikimenyetso nyacyo cy’aho akazi kari.',exactPin:'Ahantu nyako',viewGoogleMaps:'Reba kuri Google Maps',marketplace:'ISOKO RYA UMUNOTA',welcome:'Murakaza neza',timeMatters:'Igihe cyawe gifite agaciro.',trustedHelp:'Bona ubufasha bwizewe kandi butekanye.',heroCopy:'Abantu bagenzuwe, akazi gakurikiranwa, amakuru nyayo n’ubwishyu bwemezwa n’abatanga serivisi.',verifyStart:'Banza wemeze umwirondoro',activeTasks:'Imirimo iri gukorwa',taskValue:'Agaciro k’imirimo',identity:'Umwirondoro',verified:'Wemejwe',required:'Birakenewe',recentActivity:'Ibikorwa biheruka',viewAll:'Reba byose',yourTasks:'IMIRIMO YAWE',verifiedRunners:'ABAFASHA BEMEJWE',availablePeople:'Abantu bahari',browseRunners:'Reba abafasha',latestExperiences:'Ibyasangiwe biheruka',noTasks:'Nta mirimo irabaho',noTasksCopy:'Imirimo yawe izagaragara hano nyuma yo kuyitangaza cyangwa kuyemera.',noPosts:'Nta byanditswe birajya ku muryango.'},
 fr:{home:'Accueil',postTask:'Publier une tâche',findRunner:'Trouver un runner',myTasks:'Mes tâches',business:'Business',community:'Communauté',payments:'Paiements',trust:'Confiance & KYC',profile:'Profil',settings:'Paramètres',more:'Plus',search:'Rechercher',searchPlaceholder:'De quoi avez-vous besoin ?',verifiedMarketplace:'Marché vérifié',verifiedDetail:'Identité · suivi · paiements protégés',language:'Langue',location:'Localisation',createTask:'Créer une tâche',taskTitle:'Titre de la tâche',taskDetails:'Détails de la tâche',budget:'Budget (RWF)',category:'Catégorie',serviceLocation:'Lieu du service',deadline:'Échéance',completionProof:'Preuve d’exécution',publishTask:'Publier la tâche vérifiée',useGps:'Utiliser mon GPS',mapHint:'Touchez la carte pour placer précisément le point de la tâche.',exactPin:'Point exact',viewGoogleMaps:'Voir sur Google Maps',marketplace:'MARCHÉ UMUNOTA',welcome:'Bienvenue',timeMatters:'Votre temps compte.',trustedHelp:'Obtenez une aide fiable, en toute sécurité.',heroCopy:'Personnes vérifiées, étapes suivies, données réelles et paiements confirmés par les prestataires.',verifyStart:'Vérifier pour commencer',activeTasks:'Tâches actives',taskValue:'Valeur des tâches',identity:'Identité',verified:'Vérifiée',required:'Requise',recentActivity:'Activité récente',viewAll:'Tout voir',yourTasks:'VOS TÂCHES',verifiedRunners:'RUNNERS VÉRIFIÉS',availablePeople:'Personnes disponibles',browseRunners:'Voir les runners',latestExperiences:'Expériences récentes',noTasks:'Aucune tâche',noTasksCopy:'Vos tâches réelles apparaîtront ici après publication ou acceptation.',noPosts:'Aucune publication communautaire.'},
 sw:{home:'Nyumbani',postTask:'Weka kazi',findRunner:'Tafuta msaidizi',myTasks:'Kazi zangu',business:'Biashara',community:'Jumuiya',payments:'Malipo',trust:'Uaminifu & KYC',profile:'Wasifu',settings:'Mipangilio',more:'Zaidi',search:'Tafuta',searchPlaceholder:'Unahitaji kusaidiwa kufanya nini?',verifiedMarketplace:'Soko lililothibitishwa',verifiedDetail:'Utambulisho · ufuatiliaji · malipo salama',language:'Lugha',location:'Mahali',createTask:'Tengeneza kazi',taskTitle:'Kichwa cha kazi',taskDetails:'Maelezo ya kazi',budget:'Bajeti (RWF)',category:'Aina',serviceLocation:'Mahali pa huduma',deadline:'Mwisho wa muda',completionProof:'Uthibitisho wa kukamilika',publishTask:'Chapisha kazi iliyothibitishwa',useGps:'Tumia GPS yangu',mapHint:'Gusa ramani kuweka pini sahihi ya kazi.',exactPin:'Pini sahihi',viewGoogleMaps:'Fungua Google Maps',marketplace:'SOKO LA UMUNOTA',welcome:'Karibu',timeMatters:'Muda wako ni muhimu.',trustedHelp:'Pata msaada unaoaminika kwa usalama.',heroCopy:'Watu waliothibitishwa, hatua za kazi zinazofuatiliwa, data halisi na malipo yanayothibitishwa na watoa huduma.',verifyStart:'Thibitisha kuanza',activeTasks:'Kazi zinazoendelea',taskValue:'Thamani ya kazi',identity:'Utambulisho',verified:'Imethibitishwa',required:'Inahitajika',recentActivity:'Shughuli za hivi karibuni',viewAll:'Tazama zote',yourTasks:'KAZI ZAKO',verifiedRunners:'WASAIDIZI WALIOTHIBISHWA',availablePeople:'Watu waliopo',browseRunners:'Tazama wasaidizi',latestExperiences:'Uzoefu wa hivi karibuni',noTasks:'Bado hakuna kazi',noTasksCopy:'Kazi zako halisi zitaonekana hapa baada ya kuchapisha au kukubali moja.',noPosts:'Bado hakuna machapisho ya jumuiya.'}
};
const LanguageContext=createContext<{lang:Lang;setLang:(l:Lang)=>void;t:(key:string)=>string}>({lang:'en',setLang:()=>{},t:k=>k});
export function LanguageProvider({children}:{children:React.ReactNode}){const [lang,setLangState]=useState<Lang>('en');useEffect(()=>{const saved=localStorage.getItem('umunota-language') as Lang|null;if(saved&&dictionaries[saved]){setLangState(saved);document.documentElement.lang=saved==='rw'?'rw':saved}},[]);function setLang(l:Lang){setLangState(l);localStorage.setItem('umunota-language',l);document.documentElement.lang=l==='rw'?'rw':l;}const value=useMemo(()=>({lang,setLang,t:(key:string)=>dictionaries[lang][key]||dictionaries.en[key]||key}),[lang]);return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>}
export function useLanguage(){return useContext(LanguageContext)}
export const languageOptions:[Lang,string][]=[['en','English'],['rw','Ikinyarwanda'],['fr','Français'],['sw','Kiswahili']];
