'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';

type Lang='en'|'rw'|'fr'|'sw';
type Dict=Record<string,string>;
const dictionaries:Record<Lang,Dict>={
 en:{home:'Home',postTask:'Post task',findRunner:'Find runner',myTasks:'My tasks',business:'Business',community:'Community',payments:'Payments',trust:'Trust & KYC',profile:'Profile',more:'More',search:'Search',searchPlaceholder:'What do you need done?',verifiedMarketplace:'Verified marketplace',verifiedDetail:'Identity · tracked work · protected payments',language:'Language',location:'Location',createTask:'Create task',taskTitle:'Task title',taskDetails:'Task details',budget:'Budget (RWF)',category:'Category',serviceLocation:'Service location',deadline:'Deadline',completionProof:'Completion proof',publishTask:'Publish verified task',useGps:'Use my GPS',mapHint:'Tap the map to place the exact task pin.',exactPin:'Exact pin',viewGoogleMaps:'View on Google Maps'},
 rw:{home:'Ahabanza',postTask:'Tanga akazi',findRunner:'Shaka umufasha',myTasks:'Imirimo yanjye',business:'Business',community:'Umuryango',payments:'Kwishyura',trust:'Umutekano & KYC',profile:'Umwirondoro',more:'Ibindi',search:'Shaka',searchPlaceholder:'Ni iki ushaka ko bagufasha gukora?',verifiedMarketplace:'Isoko ry’abagenzuwe',verifiedDetail:'Umwirondoro · gukurikirana akazi · kwishyura neza',language:'Ururimi',location:'Aho uri',createTask:'Tanga akazi',taskTitle:'Umutwe w’akazi',taskDetails:'Ibisobanuro by’akazi',budget:'Ingengo y’imari (RWF)',category:'Icyiciro',serviceLocation:'Aho akazi gakorerwa',deadline:'Igihe ntarengwa',completionProof:'Ikimenyetso cy’uko karangiye',publishTask:'Tangaza akazi kagenzuwe',useGps:'Koresha GPS yanjye',mapHint:'Kanda ku ikarita ushyire ikimenyetso nyacyo cy’aho akazi kari.',exactPin:'Ahantu nyako',viewGoogleMaps:'Reba kuri Google Maps'},
 fr:{home:'Accueil',postTask:'Publier une tâche',findRunner:'Trouver un runner',myTasks:'Mes tâches',business:'Business',community:'Communauté',payments:'Paiements',trust:'Confiance & KYC',profile:'Profil',more:'Plus',search:'Rechercher',searchPlaceholder:'De quoi avez-vous besoin ?',verifiedMarketplace:'Marché vérifié',verifiedDetail:'Identité · suivi · paiements protégés',language:'Langue',location:'Localisation',createTask:'Créer une tâche',taskTitle:'Titre de la tâche',taskDetails:'Détails de la tâche',budget:'Budget (RWF)',category:'Catégorie',serviceLocation:'Lieu du service',deadline:'Échéance',completionProof:'Preuve d’exécution',publishTask:'Publier la tâche vérifiée',useGps:'Utiliser mon GPS',mapHint:'Touchez la carte pour placer précisément le point de la tâche.',exactPin:'Point exact',viewGoogleMaps:'Voir sur Google Maps'},
 sw:{home:'Nyumbani',postTask:'Weka kazi',findRunner:'Tafuta msaidizi',myTasks:'Kazi zangu',business:'Biashara',community:'Jumuiya',payments:'Malipo',trust:'Uaminifu & KYC',profile:'Wasifu',more:'Zaidi',search:'Tafuta',searchPlaceholder:'Unahitaji kusaidiwa kufanya nini?',verifiedMarketplace:'Soko lililothibitishwa',verifiedDetail:'Utambulisho · ufuatiliaji · malipo salama',language:'Lugha',location:'Mahali',createTask:'Tengeneza kazi',taskTitle:'Kichwa cha kazi',taskDetails:'Maelezo ya kazi',budget:'Bajeti (RWF)',category:'Aina',serviceLocation:'Mahali pa huduma',deadline:'Mwisho wa muda',completionProof:'Uthibitisho wa kukamilika',publishTask:'Chapisha kazi iliyothibitishwa',useGps:'Tumia GPS yangu',mapHint:'Gusa ramani kuweka pini sahihi ya kazi.',exactPin:'Pini sahihi',viewGoogleMaps:'Fungua Google Maps'}
};
const LanguageContext=createContext<{lang:Lang;setLang:(l:Lang)=>void;t:(key:string)=>string}>({lang:'en',setLang:()=>{},t:k=>k});
export function LanguageProvider({children}:{children:React.ReactNode}){const [lang,setLangState]=useState<Lang>('en');useEffect(()=>{const saved=localStorage.getItem('umunota-language') as Lang|null;if(saved&&dictionaries[saved])setLangState(saved)},[]);function setLang(l:Lang){setLangState(l);localStorage.setItem('umunota-language',l);document.documentElement.lang=l==='rw'?'rw':l;}const value=useMemo(()=>({lang,setLang,t:(key:string)=>dictionaries[lang][key]||dictionaries.en[key]||key}),[lang]);return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>}
export function useLanguage(){return useContext(LanguageContext)}
export const languageOptions:[Lang,string][]=[['en','English'],['rw','Ikinyarwanda'],['fr','Français'],['sw','Kiswahili']];
