'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';

type Lang='en'|'rw'|'fr'|'sw';
type Dict=Record<string,string>;
const dictionaries:Record<Lang,Dict>={
 en:{
  home:'Home',postTask:'Post task',findRunner:'Find runner',myTasks:'My tasks',business:'Business',community:'Community',payments:'Payments',trust:'Trust & KYC',profile:'Profile',settings:'Settings',more:'More',search:'Search',searchPlaceholder:'What do you need done?',verifiedMarketplace:'Verified marketplace',verifiedDetail:'Identity · tracked work · protected payments',language:'Language',location:'Location',legalSafety:'Legal & Safety',close:'Close',
  createTask:'Create task',taskTitle:'Task title',taskDetails:'Task details',budget:'Budget (RWF)',category:'Category',serviceLocation:'Service location',deadline:'Deadline',completionProof:'Completion proof',publishTask:'Publish verified task',useGps:'Use my GPS',mapHint:'Tap the map to place the exact task pin.',exactPin:'Exact pin',viewGoogleMaps:'View on Google Maps',
  marketplace:'UMUNOTA MARKETPLACE',welcome:'Welcome',timeMatters:'Your time matters.',trustedHelp:'Get trusted help, safely.',heroCopy:'Verified people, tracked task stages, real database records and provider-backed payments.',verifyStart:'Verify to start',activeTasks:'Active tasks',taskValue:'Task value',identity:'Identity',verified:'Verified',required:'Required',recentActivity:'Recent activity',viewAll:'View all',yourTasks:'YOUR TASKS',verifiedRunners:'VERIFIED RUNNERS',availablePeople:'Available people',browseRunners:'Browse runners',latestExperiences:'Latest experiences',noTasks:'No tasks yet',noTasksCopy:'Your real tasks will appear here after you publish or accept one.',noPosts:'No community posts yet.',
  notifications:'Notifications',recentUpdates:'Recent updates',markAllRead:'Mark all read',loadingNotifications:'Loading notifications...',noNotifications:'No notifications yet.',notificationSettings:'Notification settings',
  accountSettings:'ACCOUNT SETTINGS',controlAccount:'Control your UMUNOTA account',settingsIntro:'Profile, language, communications, privacy and security settings are connected to your production account.',viewProfile:'View profile',profileSection:'PROFILE',identityPublic:'Identity & public profile',changePhoto:'Change profile photo',optimizingUploading:'Optimizing & uploading...',photoHelp:'Square-cropped and compressed to WebP before upload.',email:'Email',fullName:'Full name',username:'Username',phone:'Phone',showRunner:'Show me in Find a Runner',showRunnerHelp:'Turning this off removes your profile from the verified-runner directory.',saveProfileSettings:'Save profile settings',saving:'Saving...',languageSection:'LANGUAGE',appLanguage:'App language',languageHelp:'Your choice is saved to this account and this browser.',emailSection:'EMAIL',taskNewsletter:'Task newsletter',dailyDigest:'Daily recent-task digest',dailyDigestHelp:'Receive up to three recent tasks from that day when available.',notificationsSection:'NOTIFICATIONS',pushNotifications:'Phone & browser push',pushHelp:'Receive important UMUNOTA updates even when the website is not open.',taskUpdates:'Task updates',taskUpdatesHelp:'Runner acceptance, task progress, completion, approval and dispute updates.',communityUpdates:'Community updates',communityUpdatesHelp:'Notifications related to community activity.',enablePush:'Enable push notifications',disablePush:'Disable push notifications',sendTest:'Send test notification',trustSection:'TRUST',verificationPolicies:'Verification & policies',identityVerified:'Identity verified',completeVerification:'Complete identity verification',viewRunnerDirectory:'View runner directory',securitySection:'SECURITY',passwordSessions:'Password & sessions',newPassword:'New password',confirmPassword:'Confirm new password',updating:'Updating...',changePassword:'Change password',connectedSignIn:'Connected sign-in',emailPassword:'Email/password',signOutAll:'Sign out on all devices',loadingSettings:'Loading settings...',
  communityTitle:'People, tasks and useful experiences',communityIntro:'See what UMUNOTA members are sharing. Open a post to view the complete story, media and discussion.',newPost:'New post',verifiedTaskExperience:'Verified task experience',communityPost:'Community post',viewFullPost:'View full post',likes:'likes',comments:'comments',shares:'shares',like:'Like',comment:'Comment',share:'Share',noCommunityPosts:'No community posts yet',firstShare:'Be the first to share something useful.',communityStandard:'COMMUNITY STANDARD',usefulTruthful:'Useful, truthful and respectful',communityStandardText:'Task-linked experiences can only reference real approved or paid tasks belonging to the author.',postMedia:'POST MEDIA',photosVideos:'Photos and short videos',mediaHelp:'Upload up to four files per post. Each file can be up to 20 MB.',createCommunityPost:'Create community post'
 },
 rw:{
  home:'Ahabanza',postTask:'Tanga akazi',findRunner:'Shaka umufasha',myTasks:'Imirimo yanjye',business:'Ubucuruzi',community:'Umuryango',payments:'Kwishyura',trust:'Umutekano & KYC',profile:'Umwirondoro',settings:'Igenamiterere',more:'Ibindi',search:'Shaka',searchPlaceholder:'Ni iki ushaka ko bagufasha gukora?',verifiedMarketplace:'Isoko ry’abagenzuwe',verifiedDetail:'Umwirondoro · gukurikirana akazi · kwishyura neza',language:'Ururimi',location:'Aho uri',legalSafety:'Amategeko & Umutekano',close:'Funga',
  createTask:'Tanga akazi',taskTitle:'Umutwe w’akazi',taskDetails:'Ibisobanuro by’akazi',budget:'Ingengo y’imari (RWF)',category:'Icyiciro',serviceLocation:'Aho akazi gakorerwa',deadline:'Igihe ntarengwa',completionProof:'Ikimenyetso cy’uko karangiye',publishTask:'Tangaza akazi kagenzuwe',useGps:'Koresha GPS yanjye',mapHint:'Kanda ku ikarita ushyire ikimenyetso nyacyo cy’aho akazi kari.',exactPin:'Ahantu nyako',viewGoogleMaps:'Reba kuri Google Maps',
  marketplace:'ISOKO RYA UMUNOTA',welcome:'Murakaza neza',timeMatters:'Igihe cyawe gifite agaciro.',trustedHelp:'Bona ubufasha bwizewe kandi butekanye.',heroCopy:'Abantu bagenzuwe, akazi gakurikiranwa, amakuru nyayo n’ubwishyu bwemezwa n’abatanga serivisi.',verifyStart:'Banza wemeze umwirondoro',activeTasks:'Imirimo iri gukorwa',taskValue:'Agaciro k’imirimo',identity:'Umwirondoro',verified:'Wemejwe',required:'Birakenewe',recentActivity:'Ibikorwa biheruka',viewAll:'Reba byose',yourTasks:'IMIRIMO YAWE',verifiedRunners:'ABAFASHA BEMEJWE',availablePeople:'Abantu bahari',browseRunners:'Reba abafasha',latestExperiences:'Ibyasangiwe biheruka',noTasks:'Nta mirimo irabaho',noTasksCopy:'Imirimo yawe izagaragara hano nyuma yo kuyitangaza cyangwa kuyemera.',noPosts:'Nta byanditswe birajya ku muryango.',
  notifications:'Amatangazo',recentUpdates:'Amakuru mashya',markAllRead:'Shyira byose nk’ibyasomwe',loadingNotifications:'Amatangazo arimo gupakirwa...',noNotifications:'Nta matangazo arahari.',notificationSettings:'Igenamiterere ry’amatangazo',
  accountSettings:'IGENAMITERERE RYA KONTI',controlAccount:'Genzura konti yawe ya UMUNOTA',settingsIntro:'Umwirondoro, ururimi, ubutumwa, ubwirinzi n’umutekano byose bibikwa kuri konti yawe.',viewProfile:'Reba umwirondoro',profileSection:'UMWIRONDORO',identityPublic:'Umwirondoro n’ibigaragara ku bandi',changePhoto:'Hindura ifoto y’umwirondoro',optimizingUploading:'Ifoto iratunganywa ikanoherezwa...',photoHelp:'Ifoto ikatwa kare kandi igabanywa ubunini muri WebP mbere yo koherezwa.',email:'Imeyili',fullName:'Amazina yose',username:'Izina ukoresha',phone:'Telefone',showRunner:'Nyereka muri Shaka umufasha',showRunnerHelp:'Kubizimya bikuraho umwirondoro wawe mu rutonde rw’abafasha bemejwe.',saveProfileSettings:'Bika igenamiterere ry’umwirondoro',saving:'Birimo kubikwa...',languageSection:'URURIMI',appLanguage:'Ururimi rwa porogaramu',languageHelp:'Ururimi wahisemo rubikwa kuri konti no kuri iki gikoresho.',emailSection:'IMEYILI',taskNewsletter:'Ubutumwa bw’imirimo',dailyDigest:'Incamake ya buri munsi',dailyDigestHelp:'Akira imirimo mishya igera kuri itatu yashyizweho uwo munsi.',notificationsSection:'AMATANGAZO',pushNotifications:'Amatangazo kuri telefone na browser',pushHelp:'Akira amakuru y’ingenzi ya UMUNOTA n’iyo urubuga rutafunguye.',taskUpdates:'Amakuru y’akazi',taskUpdatesHelp:'Kwemera akazi, intambwe zako, kurangiza, kwemeza n’impaka.',communityUpdates:'Amakuru y’umuryango',communityUpdatesHelp:'Amatangazo ajyanye n’ibikorwa byo ku rubuga rw’umuryango.',enablePush:'Fungura amatangazo ya push',disablePush:'Funga amatangazo ya push',sendTest:'Ohereza ikizamini cy’itangazo',trustSection:'ICYIZERE',verificationPolicies:'Kugenzura & amategeko',identityVerified:'Umwirondoro wemejwe',completeVerification:'Rangiza kugenzura umwirondoro',viewRunnerDirectory:'Reba urutonde rw’abafasha',securitySection:'UMUTEKANO',passwordSessions:'Ijambo ry’ibanga & sessions',newPassword:'Ijambo ry’ibanga rishya',confirmPassword:'Emeza ijambo ry’ibanga rishya',updating:'Birimo kuvugururwa...',changePassword:'Hindura ijambo ry’ibanga',connectedSignIn:'Uburyo bwo kwinjira buhuye',emailPassword:'Imeyili/ijambo ry’ibanga',signOutAll:'Sohoka ku bikoresho byose',loadingSettings:'Igenamiterere ririmo gupakirwa...',
  communityTitle:'Abantu, imirimo n’ubunararibonye bufite umumaro',communityIntro:'Reba ibyo abanyamuryango ba UMUNOTA basangira. Fungura inyandiko urebe ibisobanuro byose, amafoto cyangwa videwo n’ibitekerezo.',newPost:'Inyandiko nshya',verifiedTaskExperience:'Uburambe ku kazi kemejwe',communityPost:'Inyandiko y’umuryango',viewFullPost:'Reba inyandiko yose',likes:'abakunze',comments:'ibitekerezo',shares:'abasangiye',like:'Kunda',comment:'Tanga igitekerezo',share:'Sangiza',noCommunityPosts:'Nta nyandiko z’umuryango zirabaho',firstShare:'Ba uwa mbere usangiza ikintu gifite umumaro.',communityStandard:'AMAHAME Y’UMURYANGO',usefulTruthful:'Gifite umumaro, ukuri kandi cyubaha abandi',communityStandardText:'Inkuru ihujwe n’akazi ishobora gusa kuvuga ku kazi nyako kemejwe cyangwa karangiye k’umwanditsi.',postMedia:'AMAFOTO NA VIDEWO',photosVideos:'Amafoto na videwo ngufi',mediaHelp:'Ohereza dosiye zigera kuri enye kuri buri nyandiko. Buri dosiye ntirenge 20 MB.',createCommunityPost:'Kora inyandiko y’umuryango'
 },
 fr:{
  home:'Accueil',postTask:'Publier une tâche',findRunner:'Trouver un runner',myTasks:'Mes tâches',business:'Entreprise',community:'Communauté',payments:'Paiements',trust:'Confiance & KYC',profile:'Profil',settings:'Paramètres',more:'Plus',search:'Rechercher',searchPlaceholder:'De quoi avez-vous besoin ?',verifiedMarketplace:'Marché vérifié',verifiedDetail:'Identité · suivi · paiements protégés',language:'Langue',location:'Localisation',legalSafety:'Juridique & Sécurité',close:'Fermer',
  createTask:'Créer une tâche',taskTitle:'Titre de la tâche',taskDetails:'Détails de la tâche',budget:'Budget (RWF)',category:'Catégorie',serviceLocation:'Lieu du service',deadline:'Échéance',completionProof:'Preuve d’exécution',publishTask:'Publier la tâche vérifiée',useGps:'Utiliser mon GPS',mapHint:'Touchez la carte pour placer précisément le point de la tâche.',exactPin:'Point exact',viewGoogleMaps:'Voir sur Google Maps',
  marketplace:'MARCHÉ UMUNOTA',welcome:'Bienvenue',timeMatters:'Votre temps compte.',trustedHelp:'Obtenez une aide fiable, en toute sécurité.',heroCopy:'Personnes vérifiées, étapes suivies, données réelles et paiements confirmés par les prestataires.',verifyStart:'Vérifier pour commencer',activeTasks:'Tâches actives',taskValue:'Valeur des tâches',identity:'Identité',verified:'Vérifiée',required:'Requise',recentActivity:'Activité récente',viewAll:'Tout voir',yourTasks:'VOS TÂCHES',verifiedRunners:'RUNNERS VÉRIFIÉS',availablePeople:'Personnes disponibles',browseRunners:'Voir les runners',latestExperiences:'Expériences récentes',noTasks:'Aucune tâche',noTasksCopy:'Vos tâches réelles apparaîtront ici après publication ou acceptation.',noPosts:'Aucune publication communautaire.',
  notifications:'Notifications',recentUpdates:'Mises à jour récentes',markAllRead:'Tout marquer comme lu',loadingNotifications:'Chargement des notifications...',noNotifications:'Aucune notification pour le moment.',notificationSettings:'Paramètres des notifications',
  accountSettings:'PARAMÈTRES DU COMPTE',controlAccount:'Gérez votre compte UMUNOTA',settingsIntro:'Le profil, la langue, les communications, la confidentialité et la sécurité sont liés à votre compte réel.',viewProfile:'Voir le profil',profileSection:'PROFIL',identityPublic:'Identité & profil public',changePhoto:'Changer la photo de profil',optimizingUploading:'Optimisation et envoi...',photoHelp:'Recadrée au carré et compressée en WebP avant l’envoi.',email:'E-mail',fullName:'Nom complet',username:'Nom d’utilisateur',phone:'Téléphone',showRunner:'M’afficher dans Trouver un runner',showRunnerHelp:'La désactivation retire votre profil de l’annuaire des runners vérifiés.',saveProfileSettings:'Enregistrer le profil',saving:'Enregistrement...',languageSection:'LANGUE',appLanguage:'Langue de l’application',languageHelp:'Votre choix est enregistré sur ce compte et ce navigateur.',emailSection:'E-MAIL',taskNewsletter:'Newsletter des tâches',dailyDigest:'Résumé quotidien des tâches',dailyDigestHelp:'Recevez jusqu’à trois tâches récentes publiées dans la journée.',notificationsSection:'NOTIFICATIONS',pushNotifications:'Push téléphone & navigateur',pushHelp:'Recevez les mises à jour importantes d’UMUNOTA même lorsque le site est fermé.',taskUpdates:'Mises à jour des tâches',taskUpdatesHelp:'Acceptation du runner, progression, fin, approbation et litiges.',communityUpdates:'Mises à jour de la communauté',communityUpdatesHelp:'Notifications liées aux activités de la communauté.',enablePush:'Activer les notifications push',disablePush:'Désactiver les notifications push',sendTest:'Envoyer une notification test',trustSection:'CONFIANCE',verificationPolicies:'Vérification & règles',identityVerified:'Identité vérifiée',completeVerification:'Terminer la vérification',viewRunnerDirectory:'Voir l’annuaire des runners',securitySection:'SÉCURITÉ',passwordSessions:'Mot de passe & sessions',newPassword:'Nouveau mot de passe',confirmPassword:'Confirmer le nouveau mot de passe',updating:'Mise à jour...',changePassword:'Changer le mot de passe',connectedSignIn:'Connexion associée',emailPassword:'E-mail/mot de passe',signOutAll:'Se déconnecter de tous les appareils',loadingSettings:'Chargement des paramètres...',
  communityTitle:'Personnes, tâches et expériences utiles',communityIntro:'Découvrez ce que partagent les membres d’UMUNOTA. Ouvrez une publication pour voir le récit complet, les médias et la discussion.',newPost:'Nouvelle publication',verifiedTaskExperience:'Expérience de tâche vérifiée',communityPost:'Publication de la communauté',viewFullPost:'Voir la publication complète',likes:'J’aime',comments:'commentaires',shares:'partages',like:'J’aime',comment:'Commenter',share:'Partager',noCommunityPosts:'Aucune publication pour le moment',firstShare:'Soyez la première personne à partager quelque chose d’utile.',communityStandard:'RÈGLES DE LA COMMUNAUTÉ',usefulTruthful:'Utile, honnête et respectueux',communityStandardText:'Les expériences liées à une tâche ne peuvent référencer que des tâches réelles, approuvées ou payées appartenant à l’auteur.',postMedia:'MÉDIAS',photosVideos:'Photos et courtes vidéos',mediaHelp:'Ajoutez jusqu’à quatre fichiers par publication, de 20 Mo maximum chacun.',createCommunityPost:'Créer une publication'
 },
 sw:{
  home:'Nyumbani',postTask:'Weka kazi',findRunner:'Tafuta msaidizi',myTasks:'Kazi zangu',business:'Biashara',community:'Jumuiya',payments:'Malipo',trust:'Uaminifu & KYC',profile:'Wasifu',settings:'Mipangilio',more:'Zaidi',search:'Tafuta',searchPlaceholder:'Unahitaji kusaidiwa kufanya nini?',verifiedMarketplace:'Soko lililothibitishwa',verifiedDetail:'Utambulisho · ufuatiliaji · malipo salama',language:'Lugha',location:'Mahali',legalSafety:'Sheria & Usalama',close:'Funga',
  createTask:'Tengeneza kazi',taskTitle:'Kichwa cha kazi',taskDetails:'Maelezo ya kazi',budget:'Bajeti (RWF)',category:'Aina',serviceLocation:'Mahali pa huduma',deadline:'Mwisho wa muda',completionProof:'Uthibitisho wa kukamilika',publishTask:'Chapisha kazi iliyothibitishwa',useGps:'Tumia GPS yangu',mapHint:'Gusa ramani kuweka pini sahihi ya kazi.',exactPin:'Pini sahihi',viewGoogleMaps:'Fungua Google Maps',
  marketplace:'SOKO LA UMUNOTA',welcome:'Karibu',timeMatters:'Muda wako ni muhimu.',trustedHelp:'Pata msaada unaoaminika kwa usalama.',heroCopy:'Watu waliothibitishwa, hatua za kazi zinazofuatiliwa, data halisi na malipo yanayothibitishwa na watoa huduma.',verifyStart:'Thibitisha kuanza',activeTasks:'Kazi zinazoendelea',taskValue:'Thamani ya kazi',identity:'Utambulisho',verified:'Imethibitishwa',required:'Inahitajika',recentActivity:'Shughuli za hivi karibuni',viewAll:'Tazama zote',yourTasks:'KAZI ZAKO',verifiedRunners:'WASAIDIZI WALIOTHIBITISHWA',availablePeople:'Watu waliopo',browseRunners:'Tazama wasaidizi',latestExperiences:'Uzoefu wa hivi karibuni',noTasks:'Bado hakuna kazi',noTasksCopy:'Kazi zako halisi zitaonekana hapa baada ya kuchapisha au kukubali moja.',noPosts:'Bado hakuna machapisho ya jumuiya.',
  notifications:'Arifa',recentUpdates:'Taarifa za hivi karibuni',markAllRead:'Weka zote kuwa zimesomwa',loadingNotifications:'Inapakia arifa...',noNotifications:'Bado hakuna arifa.',notificationSettings:'Mipangilio ya arifa',
  accountSettings:'MIPANGILIO YA AKAUNTI',controlAccount:'Dhibiti akaunti yako ya UMUNOTA',settingsIntro:'Wasifu, lugha, mawasiliano, faragha na usalama vimeunganishwa na akaunti yako.',viewProfile:'Tazama wasifu',profileSection:'WASIFU',identityPublic:'Utambulisho & wasifu wa umma',changePhoto:'Badilisha picha ya wasifu',optimizingUploading:'Inaboresha na kupakia...',photoHelp:'Inakatwa mraba na kubanwa kuwa WebP kabla ya kupakiwa.',email:'Barua pepe',fullName:'Jina kamili',username:'Jina la mtumiaji',phone:'Simu',showRunner:'Nionyeshe kwenye Tafuta msaidizi',showRunnerHelp:'Ukizima, wasifu wako utaondolewa kwenye orodha ya wasaidizi waliothibitishwa.',saveProfileSettings:'Hifadhi mipangilio ya wasifu',saving:'Inahifadhi...',languageSection:'LUGHA',appLanguage:'Lugha ya programu',languageHelp:'Chaguo lako linahifadhiwa kwenye akaunti na kivinjari hiki.',emailSection:'BARUA PEPE',taskNewsletter:'Jarida la kazi',dailyDigest:'Muhtasari wa kazi wa kila siku',dailyDigestHelp:'Pokea hadi kazi tatu mpya zilizowekwa siku hiyo.',notificationsSection:'ARIFA',pushNotifications:'Arifa za simu & kivinjari',pushHelp:'Pokea masasisho muhimu ya UMUNOTA hata tovuti ikiwa haijafunguliwa.',taskUpdates:'Masasisho ya kazi',taskUpdatesHelp:'Kukubaliwa kwa msaidizi, maendeleo, kukamilika, idhini na migogoro.',communityUpdates:'Masasisho ya jumuiya',communityUpdatesHelp:'Arifa zinazohusiana na shughuli za jumuiya.',enablePush:'Washa arifa za push',disablePush:'Zima arifa za push',sendTest:'Tuma arifa ya majaribio',trustSection:'UAMINIFU',verificationPolicies:'Uthibitishaji & sera',identityVerified:'Utambulisho umethibitishwa',completeVerification:'Kamilisha uthibitishaji',viewRunnerDirectory:'Tazama orodha ya wasaidizi',securitySection:'USALAMA',passwordSessions:'Nenosiri & vipindi',newPassword:'Nenosiri jipya',confirmPassword:'Thibitisha nenosiri jipya',updating:'Inasasisha...',changePassword:'Badilisha nenosiri',connectedSignIn:'Njia za kuingia zilizounganishwa',emailPassword:'Barua pepe/nenosiri',signOutAll:'Toka kwenye vifaa vyote',loadingSettings:'Inapakia mipangilio...',
  communityTitle:'Watu, kazi na uzoefu wenye manufaa',communityIntro:'Tazama wanachoshiriki wanachama wa UMUNOTA. Fungua chapisho kuona maelezo kamili, picha au video na mjadala.',newPost:'Chapisho jipya',verifiedTaskExperience:'Uzoefu wa kazi iliyothibitishwa',communityPost:'Chapisho la jumuiya',viewFullPost:'Tazama chapisho lote',likes:'waliopenda',comments:'maoni',shares:'walioshiriki',like:'Penda',comment:'Toa maoni',share:'Shiriki',noCommunityPosts:'Bado hakuna machapisho ya jumuiya',firstShare:'Kuwa wa kwanza kushiriki kitu chenye manufaa.',communityStandard:'VIWANGO VYA JUMUIYA',usefulTruthful:'Chenye manufaa, ukweli na heshima',communityStandardText:'Uzoefu uliounganishwa na kazi unaweza kurejelea tu kazi halisi iliyoidhinishwa au kulipwa ya mwandishi.',postMedia:'PICHA NA VIDEO',photosVideos:'Picha na video fupi',mediaHelp:'Pakia hadi faili nne kwa chapisho. Kila faili inaweza kuwa hadi MB 20.',createCommunityPost:'Unda chapisho la jumuiya'
 }
};
const LanguageContext=createContext<{lang:Lang;setLang:(l:Lang)=>void;t:(key:string)=>string}>({lang:'en',setLang:()=>{},t:k=>k});
export function LanguageProvider({children}:{children:React.ReactNode}){const [lang,setLangState]=useState<Lang>('en');useEffect(()=>{const saved=localStorage.getItem('umunota-language') as Lang|null;if(saved&&dictionaries[saved]){setLangState(saved);document.documentElement.lang=saved==='rw'?'rw':saved}},[]);function setLang(l:Lang){setLangState(l);localStorage.setItem('umunota-language',l);document.documentElement.lang=l==='rw'?'rw':l;}const value=useMemo(()=>({lang,setLang,t:(key:string)=>dictionaries[lang][key]||dictionaries.en[key]||key}),[lang]);return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>}
export function useLanguage(){return useContext(LanguageContext)}
export const languageOptions:[Lang,string][]=[['en','English'],['rw','Ikinyarwanda'],['fr','Français'],['sw','Kiswahili']];
