'use client';
import {useEffect,useRef,useState} from 'react';
import {Crosshair,MapPin} from 'lucide-react';
import {useLanguage} from './LanguageProvider';

declare global{interface Window{L?:any}}
export default function LocationPicker({latitude,longitude,onChange}:{latitude:number|null;longitude:number|null;onChange:(lat:number,lng:number,accuracy?:number)=>void}){const mapEl=useRef<HTMLDivElement|null>(null);const mapRef=useRef<any>(null);const markerRef=useRef<any>(null);const [gpsBusy,setGpsBusy]=useState(false);const [error,setError]=useState('');const {t}=useLanguage();
 useEffect(()=>{let cancelled=false;const ensure=async()=>{if(!document.querySelector('link[data-leaflet]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.leaflet='1';document.head.appendChild(l)}if(!window.L){await new Promise<void>((resolve,reject)=>{const existing=document.querySelector('script[data-leaflet]') as HTMLScriptElement|null;if(existing){existing.addEventListener('load',()=>resolve(),{once:true});return}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.dataset.leaflet='1';s.onload=()=>resolve();s.onerror=()=>reject(new Error('Map library failed to load'));document.body.appendChild(s)})}if(cancelled||!mapEl.current||mapRef.current)return;const L=window.L;const start:[number,number]=latitude!=null&&longitude!=null?[latitude,longitude]:[-1.9441,30.0619];const map=L.map(mapEl.current,{zoomControl:true}).setView(start,latitude!=null?16:12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);map.on('click',(e:any)=>{const {lat,lng}=e.latlng;onChange(Number(lat.toFixed(7)),Number(lng.toFixed(7)));});mapRef.current=map};ensure().catch(()=>setError('Map could not load. GPS and coordinates can still be used.'));return()=>{cancelled=true;mapRef.current?.remove();mapRef.current=null}},[]);
 useEffect(()=>{const L=window.L;if(!L||!mapRef.current||latitude==null||longitude==null)return;if(markerRef.current)markerRef.current.setLatLng([latitude,longitude]);else markerRef.current=L.marker([latitude,longitude]).addTo(mapRef.current);mapRef.current.setView([latitude,longitude],16)},[latitude,longitude]);
 function useGps(){if(!navigator.geolocation){setError('GPS is not available in this browser.');return}setGpsBusy(true);setError('');navigator.geolocation.getCurrentPosition(p=>{onChange(Number(p.coords.latitude.toFixed(7)),Number(p.coords.longitude.toFixed(7)),p.coords.accuracy);setGpsBusy(false)},()=>{setError('Location permission was denied or unavailable. You can still tap the map.');setGpsBusy(false)},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
 return <div className="locationPicker"><div className="locationPickerHead"><div><b><MapPin size={16}/>{t('exactPin')}</b><small>{t('mapHint')}</small></div><button type="button" className="btn btn-dark" onClick={useGps} disabled={gpsBusy}><Crosshair size={16}/>{gpsBusy?'Locating...':t('useGps')}</button></div><div ref={mapEl} className="locationMap" aria-label="Exact task location map"/>{latitude!=null&&longitude!=null&&<div className="coordinateBar"><span>{latitude.toFixed(6)}, {longitude.toFixed(6)}</span><a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${latitude},${longitude}`}>{t('viewGoogleMaps')}</a></div>}{error&&<small className="locationError">{error}</small>}</div>}
