import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowLeft,ExternalLink,FileCheck2,ShieldCheck,UserRoundCheck} from 'lucide-react';
import {requireAdmin} from '@/lib/admin';
import {createAdminSupabaseClient} from '@/lib/supabase-admin';
import {setKycStatus} from '../../actions';
export const dynamic='force-dynamic';

function yes(v:boolean|null|undefined){return v?'Accepted':'Not accepted'}
export default async function KycApplicationDetails({params}:{params:Promise<{userId:string}>}){
 await requireAdmin();const{userId}=await params;const admin=createAdminSupabaseClient();
 const{data:a}=await admin.from('kyc_applications').select('*').eq('user_id',userId).maybeSingle();if(!a)notFound();
 const[{data:profile},{data:authUser},front,back]=await Promise.all([
  admin.from('profiles').select('id,full_name,username,phone,role,kyc_status,created_at,updated_at').eq('id',userId).maybeSingle(),
  admin.auth.admin.getUserById(userId),
  admin.storage.from('kyc-documents').createSignedUrl(a.id_front_path,600),
  admin.storage.from('kyc-documents').createSignedUrl(a.id_back_path,600)
 ]);
 const frontUrl=front.data?.signedUrl||'';const backUrl=back.data?.signedUrl||'';
 return <><header className="adminPageHeader"><div><Link href="/admin/kyc" className="backLink"><ArrowLeft size={16}/> KYC queue</Link><span className="eyebrow">KYC APPLICATION DETAILS</span><h1>{a.full_legal_name}</h1><p>Complete application data submitted by this user. Identity document links are private and expire automatically.</p></div><span className="taskState">{a.status}</span></header>
 <div className="adminKycDetailGrid"><section className="adminListCard adminKycDetailCard"><div className="settingsSectionTitle"><UserRoundCheck/><div><span className="eyebrow">PERSONAL INFORMATION</span><h2>Identity and contact</h2></div></div><dl className="adminKycData"><div><dt>Full legal name</dt><dd>{a.full_legal_name}</dd></div><div><dt>Username</dt><dd>{a.username||'—'}</dd></div><div><dt>Email</dt><dd>{authUser.user?.email||'—'}</dd></div><div><dt>Phone</dt><dd>{a.phone}</dd></div><div><dt>Date of birth</dt><dd>{a.date_of_birth}</dd></div><div><dt>Nationality</dt><dd>{a.nationality}</dd></div><div><dt>District / city</dt><dd>{a.district}</dd></div><div><dt>Address / area</dt><dd>{a.address||'—'}</dd></div><div><dt>Current account role</dt><dd>{profile?.role||'—'}</dd></div><div><dt>Current verification state</dt><dd>{profile?.kyc_status||'—'}</dd></div></dl></section>
 <section className="adminListCard adminKycDetailCard"><div className="settingsSectionTitle"><FileCheck2/><div><span className="eyebrow">IDENTITY DOCUMENT</span><h2>Document review</h2></div></div><dl className="adminKycData"><div><dt>Document type</dt><dd>{a.identity_type}</dd></div><div><dt>Document number</dt><dd>{a.identity_number}</dd></div></dl><div className="adminKycDocs">{frontUrl?<a className="btn btn-dark" href={frontUrl} target="_blank" rel="noreferrer"><ExternalLink size={16}/> View front document</a>:<span className="errorBox">Front document unavailable</span>}{backUrl?<a className="btn btn-dark" href={backUrl} target="_blank" rel="noreferrer"><ExternalLink size={16}/> View back document</a>:<span className="errorBox">Back document unavailable</span>}</div><p className="muted">Private document links expire in 10 minutes. Do not copy or share them.</p></section>
 <section className="adminListCard adminKycDetailCard"><span className="eyebrow">MARKETPLACE EXPERIENCE</span><h2>How the user plans to use UMUNOTA</h2><dl className="adminKycData"><div><dt>Marketplace role</dt><dd>{a.marketplace_role}</dd></div><div><dt>Previous task experience</dt><dd>{a.task_experience||'—'}</dd></div><div className="wide"><dt>Expectations</dt><dd>{a.work_expectations||'—'}</dd></div><div className="wide"><dt>Safety response</dt><dd>{a.safety_answer}</dd></div></dl></section>
 <section className="adminListCard adminKycDetailCard"><div className="settingsSectionTitle"><ShieldCheck/><div><span className="eyebrow">AGREEMENTS</span><h2>Contract acknowledgements</h2></div></div><dl className="adminKycData"><div><dt>Revenue rules</dt><dd>{yes(a.revenue_acknowledged)}</dd></div><div><dt>Payment process</dt><dd>{yes(a.payment_acknowledged)}</dd></div><div><dt>Terms & Conditions</dt><dd>{yes(a.terms_accepted)}</dd></div><div><dt>Privacy Policy</dt><dd>{yes(a.privacy_accepted)}</dd></div><div><dt>Safety Policy</dt><dd>{yes(a.safety_accepted)}</dd></div><div><dt>Contract version</dt><dd>{a.contract_version}</dd></div><div><dt>Submitted</dt><dd>{new Date(a.submitted_at).toLocaleString()}</dd></div><div><dt>Reviewed</dt><dd>{a.reviewed_at?new Date(a.reviewed_at).toLocaleString():'Not reviewed yet'}</dd></div><div className="wide"><dt>Review notes</dt><dd>{a.admin_notes||'No notes'}</dd></div></dl></section>
 <section className="adminListCard adminKycDecision"><span className="eyebrow">REVIEW DECISION</span><h2>Update verification state</h2><p>Approve only after checking the submitted information and identity documents.</p><form action={setKycStatus} className="adminInline"><input type="hidden" name="user_id" value={userId}/><select name="kyc_status" defaultValue={a.status==='approved'?'verified':a.status}><option value="pending">pending</option><option value="needs_review">needs review</option><option value="verified">verified</option><option value="rejected">rejected</option></select><button className="btn btn-gold">Save decision</button></form></section></div></>;
}
