import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Clock3} from 'lucide-react';

type Section={title:string;body:string};
const docs:Record<string,{title:string;intro:string;sections:Section[]}>= {
 terms:{title:'Terms & Conditions',intro:'These Terms govern use of UMUNOTA, a task marketplace operated as a project of Tian Group Innovation Ltd.',sections:[
  {title:'1. Marketplace role',body:'UMUNOTA provides technology for customers to post safe and lawful tasks and for eligible runners to accept work. Unless expressly stated in a separate written agreement, Tian Group Innovation Ltd is not the employer of independent runners and does not guarantee that every task will be matched, completed or suitable.'},
  {title:'2. Eligibility and verification',body:'Paid marketplace participation is intended for adults who can legally enter agreements. Identity verification may be required before posting, accepting, receiving payout or using higher-risk account features. Users must provide accurate information and must not bypass verification, age, safety or account controls.'},
  {title:'3. Tasks and prohibited activity',body:'Users may only post and accept safe, lawful everyday tasks. Tasks involving illegal activity, controlled or age-restricted goods or services, weapons, sexual services or explicit content, gambling errands, dangerous challenges, fraud, harassment, exploitation, unauthorized access, or instructions intended to evade law or platform controls are prohibited.'},
  {title:'4. Location and task information',body:'Customers are responsible for providing accurate task details, deadlines, budgets and only the location information reasonably necessary to perform the task. Exact GPS coordinates may be shared with authorized task participants when a precise pin is attached.'},
  {title:'5. Payments and fees',body:'Payment requests may be processed by licensed or authorized third-party payment providers. A status shown by UMUNOTA is not treated as final payment confirmation until the configured provider confirms it. Platform fees must be displayed before a charge is authorized.'},
  {title:'6. Completion, disputes and refunds',body:'Users should use task evidence, messages, receipts where appropriate and the task audit trail to resolve disagreements. UMUNOTA may pause task completion or payout while reviewing a dispute. Any refund depends on provider status, the facts of the task, applicable law and the published Payments, Fees & Refunds Policy.'},
  {title:'7. Community and media',body:'Community posts, comments, images and videos must follow the Community Guidelines. Users must have the right to upload content and must respect privacy, intellectual property and the dignity and safety of others.'},
  {title:'8. Suspension and enforcement',body:'Tian Group Innovation Ltd may restrict or suspend access when reasonably necessary for safety, fraud prevention, legal compliance, payment integrity, repeated policy violations or protection of users and the platform.'},
  {title:'9. No legal or professional guarantee',body:'UMUNOTA does not guarantee that a user is professionally licensed, qualified for regulated work, or suitable for every task merely because identity verification succeeded. Users should not use the marketplace for services that legally require a license unless the required credentials are independently verified.'},
  {title:'10. Governing law and review',body:'These Terms are intended to operate under applicable law in Rwanda. They are a product policy draft and should be reviewed and adapted by qualified counsel for Tian Group Innovation Ltd before final publication and commercial reliance.'}
 ]},
 privacy:{title:'Privacy Policy',intro:'This policy describes how Tian Group Innovation Ltd handles personal data through UMUNOTA.',sections:[
  {title:'Information we process',body:'Depending on your use of UMUNOTA, data may include account identity and contact information, KYC status and provider references, task details, GPS coordinates or location text, payment references and status, messages, ratings, community posts, photos and videos, device/network information, language and newsletter preferences, and audit/security records.'},
  {title:'Why we process it',body:'We process data to create and secure accounts, verify eligibility, operate and match tasks, show task locations to authorized participants, support payments and disputes, moderate community content, provide customer support, send requested or permitted communications, detect abuse, comply with legal obligations and improve reliability.'},
  {title:'Location data',body:'Exact latitude and longitude are optional unless necessary for a task. When a customer attaches an exact pin, UMUNOTA stores those coordinates with the task and may display them to users who can access that task. Users should avoid sharing home or sensitive-location data when a broader pickup point is sufficient.'},
  {title:'Identity/KYC data',body:'UMUNOTA should minimize storage of identity documents. Where an external verification provider performs the identity check, UMUNOTA should prefer storing verification status, provider session/reference and necessary audit data rather than publicly exposing identity documents.'},
  {title:'Community media',body:'Photos and videos uploaded to Community may be visible to other signed-in users according to platform visibility rules. Do not upload another person’s private information or media without an appropriate right or permission.'},
  {title:'Sharing and processors',body:'Data may be processed by service providers used for hosting, authentication, identity verification, storage, maps, email delivery, payments, security and analytics. Processor relationships should be covered by appropriate written agreements and access limited to what is necessary.'},
  {title:'Retention and security',body:'Data should be retained only as long as necessary for the purpose, contractual or legal recordkeeping, safety, fraud prevention and dispute handling. Tian Group Innovation Ltd should maintain access controls, encryption where appropriate, backups, logging, incident handling and least-privilege administration.'},
  {title:'Your rights',body:'Subject to applicable law, users may have rights to access, correct, object, restrict, erase or obtain portability of personal data, withdraw consent where consent is the legal basis, and raise complaints with the competent supervisory authority.'},
  {title:'Children and age',body:'UMUNOTA’s paid marketplace should not be used to bypass age restrictions. Where personal data of a child under the threshold set by applicable law is knowingly processed, the required parental-responsibility consent and safeguards must be implemented.'},
  {title:'Contact and updates',body:'Tian Group Innovation Ltd should publish a dedicated privacy contact/DPO channel before launch. Material policy changes should be dated and communicated where required.'}
 ]},
 safety:{title:'Safety & Acceptable Use',intro:'UMUNOTA is for ordinary, safe and lawful local help.',sections:[
  {title:'Allowed use',body:'Examples include ordinary shopping for non-restricted goods, document pickup, lawful parcel delivery, repair drop-off/collection, laundry errands, printing and other everyday services that can be performed safely and legally.'},
  {title:'Prohibited tasks',body:'Do not post or accept tasks involving illegal conduct, dangerous or age-restricted products or services, weapons, controlled substances, sexual or explicit services, gambling, dangerous challenges, fraud, threats, stalking, harassment, exploitation, unauthorized system/account access, or evasion of identity, age, payment or legal controls.'},
  {title:'Personal safety',body:'Use public or appropriate meeting points where possible, keep task communication in the platform, do not share unnecessary personal information, review task scope before accepting, and stop/report a task if circumstances materially differ from what was posted or become unsafe.'},
  {title:'Regulated services',body:'UMUNOTA identity verification is not a professional license. Work requiring a legal permit, certification or professional license should not proceed unless the necessary credential requirements are independently satisfied.'},
  {title:'Reporting',body:'Users should be able to report unsafe tasks, fraud, harassment, harmful community content, privacy violations and payment issues. Serious emergencies should be directed to appropriate local emergency or law-enforcement services rather than treated only as a platform support issue.'}
 ]},
 community:{title:'Community Guidelines',intro:'Community is for useful, truthful and respectful task-related discussion.',sections:[
  {title:'Be authentic',body:'Share your own experience and do not impersonate another person or fabricate a completed task, rating, payment outcome or identity status.'},
  {title:'Photos and videos',body:'Only upload media you have the right to share. Avoid exposing identity documents, private addresses, payment credentials, children’s personal data, private conversations or bystanders who have not agreed to public sharing.'},
  {title:'Respect and safety',body:'No harassment, threats, hate, bullying, sexual or explicit content, graphic violence, instructions for dangerous acts, scams, spam or promotion of prohibited marketplace activity.'},
  {title:'Comments, likes and shares',body:'Engagement tools must not be used to coordinate harassment, manipulate reputation or mislead users. Sharing a UMUNOTA link does not transfer ownership of another user’s content.'},
  {title:'Moderation',body:'UMUNOTA may remove content, limit reach, disable media or suspend accounts when content violates these rules, law, privacy rights, intellectual property rights or marketplace safety standards.'}
 ]},
 payments:{title:'Payments, Fees & Refunds',intro:'UMUNOTA keeps marketplace payment records linked to tasks while payment execution is handled through configured providers.',sections:[
  {title:'Provider confirmation',body:'Funding and payout are not considered final merely because a user clicked a button. UMUNOTA should reconcile provider references and signed provider callbacks before marking payment states as successful.'},
  {title:'Task service fees',body:'Any UMUNOTA service fee should be clearly shown before payment authorization. Admin-configured fees must not be silently added after the user has authorized a total.'},
  {title:'Payouts',body:'Runner payout eligibility depends on the task lifecycle, customer approval or dispute resolution, identity/KYC status and successful provider confirmation.'},
  {title:'Refunds and disputes',body:'Refund availability depends on whether funds were actually collected, provider capabilities, task status, evidence, applicable law and the outcome of any dispute review. UMUNOTA should not promise a refund that the provider has not processed.'},
  {title:'Records and taxes',body:'Users remain responsible for their own tax, accounting or business obligations unless law or a written agreement states otherwise. UMUNOTA Business records are operational records and not a substitute for professional tax advice.'}
 ]},
 cookies:{title:'Cookies & Local Storage',intro:'UMUNOTA uses browser storage and cookies needed to operate and remember user choices.',sections:[
  {title:'Essential session data',body:'Authentication cookies and related security data are used to keep users signed in and protect authenticated routes.'},
  {title:'Preferences',body:'Local storage may remember language selection, installation/banner state and other product preferences so users do not need to select them again on every visit.'},
  {title:'Analytics and optional technologies',body:'Any non-essential analytics, advertising or tracking technology should be documented and, where required, presented with appropriate consent controls before activation.'},
  {title:'Controls',body:'Users can manage browser cookies/storage through their browser and should be given in-product controls for optional communications and other consent-based processing where applicable.'}
 ]}
};
export function generateStaticParams(){return Object.keys(docs).map(slug=>({slug}))}
export default async function LegalDoc({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const doc=docs[slug];if(!doc)notFound();return <main className="legalPage"><section className="legalHero"><Link className="landingBrand simpleLandingBrand" href="/"><Clock3 size={23}/><b>UMUNOTA</b></Link><span className="eyebrow">TIAN GROUP INNOVATION LTD</span><h1>{doc.title}</h1><p>{doc.intro}</p></section><article className="legalDoc">{doc.sections.map(s=><section key={s.title}><h2>{s.title}</h2><p>{s.body}</p></section>)}</article><div className="legalFooterLinks"><Link href="/legal">Legal & Safety Center</Link><Link href="/legal/privacy">Privacy</Link><Link href="/legal/safety">Safety</Link><Link href="/tian">Tian Group projects</Link></div></main>}
