'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useState} from 'react';
import {createClient} from '@/lib/supabase';
import {Chrome,Clock3} from 'lucide-react';

const LEGAL_VERSION='2026-09-08';
export default function Signup(){
 const router=useRouter(); const [agree,setAgree]=useState(false); const [err,setErr]=useState(''); const [busy,setBusy]=useState(false);const [googleBusy,setGoogleBusy]=useState(false);
 function language(){return localStorage.getItem('umunota-language')||'en'}
 async function google(){setErr('');if(!agree){setErr('Accept the Terms, Privacy Policy and Safety rules before continuing with Google.');return}setGoogleBusy(true);try{const supabase=createClient();const lang=language();const callback=new URL('/auth/callback',location.origin);callback.searchParams.set('next','/kyc');callback.searchParams.set('legal',LEGAL_VERSION);callback.searchParams.set('language',lang);const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:callback.toString()}});if(error){setErr(error.message);setGoogleBusy(false)}}catch(e){setErr(e instanceof Error?e.message:'Google sign-up is unavailable.');setGoogleBusy(false)}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setErr('');const f=new FormData(e.currentTarget);const name=String(f.get('name')||'').trim();const email=String(f.get('email')||'').trim();const phone=String(f.get('phone')||'').trim();const password=String(f.get('password')||'');if(name.length<2||!email.includes('@')||password.length<8||!agree){setErr('Complete all fields, use at least 8 password characters and accept the Terms, Privacy Policy and Safety rules.');return}setBusy(true);try{const supabase=createClient();const lang=language();const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name,phone,legal_acceptance_version:LEGAL_VERSION,language:lang},emailRedirectTo:`${location.origin}/auth/callback?next=/kyc`}});if(error){setErr(error.message);return}router.push('/kyc')}catch(e){setErr(e instanceof Error?e.message:'Unable to create your account.')}finally{setBusy(false)}}
 return <main className="authPage"><div className="authBrand officialAuthBrand"><img src="/umunota-logo-dark.svg" alt="UMUNOTA — Tasks. People. A Better Tomorrow."/><small>A Tian Group Innovation Ltd project</small></div><form className="authCard" onSubmit={submit}><span className="eyebrow">CREATE VERIFIED ACCOUNT</span><h1>Join UMUNOTA</h1><p>Marketplace participation requires identity verification. Paid task participation is intended for users who can legally enter the marketplace agreement.</p><label className="checkRow"><input type="checkbox" checked={agree} onChange={e=>setAgree(e.target.checked)}/><span><b>I agree to UMUNOTA’s legal and safety rules</b><small>I agree to the <Link href="/legal/terms" target="_blank">Terms & Conditions</Link>, acknowledge the <Link href="/legal/privacy" target="_blank">Privacy Policy</Link>, and agree to the <Link href="/legal/safety" target="_blank">Safety & Acceptable Use Policy</Link>. Policy version {LEGAL_VERSION}.</small></span></label><button disabled={googleBusy||busy} type="button" className="oauthBtn oauthPrimary asyncBtn" onClick={google}>{googleBusy?<><Clock3 size={18} className="spinIcon"/> Connecting to Google...</>:<><Chrome size={18}/> Continue with Google</>}</button><div className="authDivider"><span>or create an account with email</span></div><div className="field"><label>Full legal name</label><input name="name" required placeholder="Your legal name" autoComplete="name"/></div><div className="grid twocol"><div className="field"><label>Email</label><input name="email" required type="email" placeholder="you@example.com" autoComplete="email"/></div><div className="field"><label>Phone</label><input name="phone" required type="tel" placeholder="+250 7..." autoComplete="tel"/></div></div><div className="field"><label>Password</label><input name="password" required type="password" placeholder="8+ characters" autoComplete="new-password"/></div>{err&&<div className="errorBox">{err}</div>}<button disabled={busy||googleBusy} className="btn btn-gold btn-wide asyncBtn" aria-busy={busy}>{busy?<><Clock3 size={18} className="spinIcon"/> Creating account...</>:<><Clock3 size={18}/> Create account with email</>}</button><div className="authFoot"><span>Already have an account?</span><Link href="/login">Sign in</Link></div><div className="legalFooterLinks"><Link href="/legal">Legal & Safety Center</Link><Link href="/tian">Tian Group Innovation Ltd</Link></div></form></main>;
}
